### ISSUE TITLE
How can I change the highlight color of the Remote Repositories icon in the status bar and can I keep it consistent with other icons?

### ISSUE THREAD

**Issue by ouweiya** [microsoft/vscode-remote-repositories-github#1]
How can I change the highlight color of the Remote Repositories icon in the status bar and can I keep it consistent with other icons?

Eye-catching colors distract me and I want to keep the harmony like the icons around me.

![image](https://user-images.githubusercontent.com/28357731/121623945-330e7e80-caa3-11eb-888e-73a38fb4e25d.png)

I hope so.

![image](https://user-images.githubusercontent.com/28357731/121624360-f55e2580-caa3-11eb-93c8-ccd1848b2a80.png)

```css
background-color: rgb(172, 98, 24);

```
change to
```css
background-color: rgb(65, 67, 57);
```

**Comment by sourvinos** [comment]
In your settings.json under "workbench.colorCustomizations": add this line: {"statusBarItem.remoteBackground": "#ff0000"} and change the value to whatever you want, say "#000000"
