### ISSUE TITLE
If a repository is deleted from github it breaks the lookups for all previously opened repositories.

### ISSUE THREAD

**Issue by ChrisThackrey** [microsoft/vscode-remote-repositories-github#10]
Issue Type: <b>Bug</b>

After opening many repos remotely, one of those repos no longer exists, breaking lookup chain. Getting the error: "Could not resolve to a Repository with the name 'nour-d/React-Library-Search'.", which references a library that is now deleted/removed from Github but Remote Repositories is still trying to access it. This seems to be preventing extension from listing all the other visited repos.

Edit: It would be a nice quality of life thing if Remote Repositories could poll the list of opened repositories and if a repo has been deleted/removed from Github the extension automatically removes that entry and all search indexes associated with that repo.

Extension version: 0.10.1
VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:22:31.215Z)
OS version: Darwin x64 20.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|17, 17, 24|
|Memory (System)|16.00GB (1.14GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by eamodio** [comment]
I've fixed the bug here, but I'm not sure I want to go pinging GitHub for every repository in that list. If you feel strongly that you want to know when a repository has been deleted, please open a new feature request. Thanks!

**Comment by eamodio** [comment]
This has been resolved in the latest Remote Repositories insiders edition.

If you want to verify this fix, you can install the Remote Repositories insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=GitHub.remotehub-insiders).

Please be sure to disable or uninstall the stable version of Remote Repositories first. Also note, that no data is shared between the insiders and stable editions.
