### ISSUE TITLE
"Unable to commit" message

### ISSUE THREAD

**Issue by ryanflorence** [microsoft/vscode-remote-repositories-github#104]
When reviewing PRs on https://github.com/remix-run/react-router and https://github.com/remix-run/remix-run I hit "." to get into the in-browser vscode, make a change, and then try to commit but I get this popping up in the bottom corner every time:

![image](https://user-images.githubusercontent.com/100200/146488449-982b93a5-087d-4047-915f-5b59b613d6ec.png)

Am I supposed to be able to commit or no? If yes, is there a setting I need to change in vscode, the plugin, or the repository?

A few random things that may or may not matter:

- I'm an admin on the repos
- I'm logged into vscode so settings are synching

Thanks!

**Comment by joyceerhl** [comment]
Are these pull requests created from branches on repos that you don't have write access to? If so, you're likely encountering a known issue with the GitHub API where maintainers can't commit to pull requests even with the 'Maintainers can write' permission enabled on the pull request. There is a fix for this in the GitHub GraphQL API that is currently in review. When that is deployed we'll be able to resolve this issue.

**Comment by joyceerhl** [comment]
The permissions bug has been fixed in the GitHub GraphQL API (thanks @brasic!). I verified that I can now commit to PR branches originating from a fork when using insiders.vscode.dev (where `"remoteHub.experimental.useNewCommitApi"` is enabled by default).

@ryanflorence @TylerLeonhardt @roblourens, could you please let me know if you're now also able to commit to PR branches originating from a fork when you use insiders.vscode.dev? If so, I will look into enabling that API for all users this iteration.

**Comment by roblourens** [comment]
Worked for me, thanks!

**Comment by meganrogge** [comment]
@roblourens did you verify this?

**Comment by kbrowne8** [comment]
Hello, I came across this issue and am getting a similar error. I'm also using the dev function of the browser Github and am an admin for the repo. Each time I try to make a commit, I see this error:

<img width="392" alt="image" src="https://user-images.githubusercontent.com/14627314/206810124-d92e0d81-73c3-4356-b122-f3cc6c0185b4.png">

Is there anything I can try to resolve this? Thanks!

**Comment by joyceerhl** [comment]
@kbrowne8 Would you mind enabling debug logging with the following settings:

```
"remoteHub.logLevel": "debug",
"githubRepositories.logLevel": "debug"
```

and providing the full debug logs for the Remote Repositories and GitHub Repositories output channels? Thank you!
