### ISSUE TITLE
Provided credentials do not have the required access

### ISSUE THREAD

**Issue by RikkiGibson** [microsoft/vscode-remote-repositories-github#108]
Version: 1.63.2
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:36:48.576Z
Browser: Microsoft Edge Version 97.0.1072.62 (Official build) (64-bit)

Steps to Reproduce:

1. Open https://github.dev/dotnet/roslyn/pull/57667
2. Navigate to a file
3. Observe the following pop-up in the lower right:

![image](https://user-images.githubusercontent.com/5833655/150028063-dc0abc39-b200-4210-9d10-f996cc2a9c78.png)

Possibly related to #97?

**Comment by joyceerhl** [comment]
Closing as this is no longer reproducible for me and was likely fixed with improved integration with [anycode](https://github.com/microsoft/vscode-anycode). Please reopen if this still persists for you.
