### ISSUE TITLE
Roadmap for the extension

### ISSUE THREAD

**Issue by GitMensch** [microsoft/vscode-remote-repositories-github#11]
> As a GitHub published extension tied to the GitHub service, open sourcing is not currently on the extension roadmap.

_Originally posted by @bamurtaugh in https://github.com/microsoft/vscode-remote-repositories-github/issues/6#issuecomment-860836772_

Roadmaps are nice, sharing those with the community helps to know what to expect / wish for. Can you please share the roadmap (even if it is "loose") as part of the docs?

**Comment by eamodio** [comment]
We will be following the same format as VS Code for roadmap/plans -- you can see the June plan here: https://github.com/microsoft/vscode-remote-repositories-github/issues/12

**Comment by GitMensch** [comment]
> We will be following the same format as VS Code for roadmap/plans

Sounds good. Where is the roadmap for this extension (and for VS code)?

**Comment by eamodio** [comment]
We don't have a public roadmap, just our iteration plans.

**Comment by GitMensch** [comment]
OK then, I think I was confused by:

> Thank you for the interest! As a GitHub published extension tied to the GitHub service, open sourcing is not currently on the extension roadmap.

_Originally posted by @bamurtaugh in https://github.com/microsoft/vscode-remote-repositories-github/issues/6#issuecomment-860836772_

And now conclude that means "if it isn't explicit state in neither of the README nor in one of the iteration plans - it isn't on the roadmap", and the citation meaning "and for this specific request (open-sourcing this extension like github desktop) it won't come in".

**Comment by eamodio** [comment]
While we don't have a _public_ roadmap, it doesn't mean we don't have _a_ roadmap. And currently open-sourcing is not currently on our plans.

IMO, the way to think about it is, things stated in the README or in an iteration plan are things definitely "planned" to be added to the extension, but just because something isn't mentioned doesn't necessarily mean it isn't on the roadmap.
