### ISSUE TITLE
Add an option to send an empty commit in github.dev/vscode.dev

### ISSUE THREAD

**Issue by sugatoray** [microsoft/vscode-remote-repositories-github#110]
Currently if you try using the vscode git UI, you can only send a commit, if some changes have been made to the code base. It would be nice to have an option of sending an empty commit using the UI.

![image](https://user-images.githubusercontent.com/10201242/147802744-e3401f88-516a-420a-8245-54f5aaf12c2e.png)

Here's a scenario where it could be helpful. Say, you have a repository which runs various CI's. But you don't want to change anything in the code base. You only want to send an empty commit, such that the CI(s) are triggered because of the commit. Yes, I can issue the following [command](https://stackoverflow.com/questions/20138640/pushing-empty-commits-to-remote) from the command line. But, I can't if I am using `github.dev` (without a command line/codespaces).

```sh
git commit --allow-empty -m "This is an empty commit"
```

> **An example**: 
>
> When conda-forge feedstock's are created, sometimes you would need to send a PR with an empty commit, to trigger building the package(s) on conda-forge channel. I find it quite useful to work on the conda-forge PR's from `github.dev`. So, allowing to send an empty commit with an optional message would be really helpful.

**Comment by joyceerhl** [comment]
This will be available with the next release of RemoteHub. We ship with the rest of VS Code in ~2 weeks.
![image](https://user-images.githubusercontent.com/30305945/150575682-4289a7cc-814d-4bb5-b230-2a7e00fd0d4c.png)

Note for team feature verification during endgame--please ping me for a VSIX.

**Comment by sugatoray** [comment]
@joyceerhl Woohoo!! 🔥🚀

**Comment by sugatoray** [comment]
@joyceerhl Could there be another feature, where you can basically pass on a git command on GitHub.dev using VSCode command pallet?

This would allow people to use any command as they need. And based on the usage of such commands on GitHub.dev, you could keep adding more formalized git commands as new features.

**Comment by lramos15** [comment]
@joyceerhl Looks like the pre-release VSIX I have doesn't have this feature. I think I need a different one :)

**Comment by lramos15** [comment]
Verified. It's a bit weird that I must write the message in the SCM view and then go to the command palette to make the actual commit
