### ISSUE TITLE
Organization access is missing

### ISSUE THREAD

**Issue by siddharthvellore** [microsoft/vscode-remote-repositories-github#112]
Steps to Reproduce:

1. Navigate to https://vscode.dev/ and grant access to "Remote repositories".
2. Able to access personal repositories.
3. No access to connected orgs.

**Comment by siddharthvellore** [comment]
Hello Joyce,
I only get authenticated to private repositories and I don’t see any option to re authenticate.

Regards,
Sid

Outlook<https://aka.ms/qtex0l> for iOS
________________________________

**Comment by joyceerhl** [comment]
@TylerLeonhardt do you happen to know when/how the organization authorization dialog above gets triggered?

**Comment by TylerLeonhardt** [comment]
Not being authorized for any org should show this... I think I'm a bit confused by the issue. Could you share a gif/video with us?

**Comment by joyceerhl** [comment]
This isn't actionable until we obtain the requested gif/video, thus closing for now. Please reopen/file an issue with additional details.
