### ISSUE TITLE
Insufficient permissions message shown when accessing personal repos without SSO enabled

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-remote-repositories-github#113]
This should not happen unless the user is trying to access a repository that is part of an organization that requires SSO.

**Comment by joyceerhl** [comment]
I was just able to reproduce this from the vscode.dev route.
1. Access vscode.dev
2. Sign out of GitHub 
3. Click on Open Remote Repository
4. Click on Open Repository from GitHub
5. :bug: Get a dialog that says 'The provided credentials do not have the required access. Would you like to reauthenticate to grant additional access?'

**Comment by joyceerhl** [comment]
Closing as I've pushed two improvements here:
1. When not SSO-ed to all orgs, previously Open Remote Repository > Open Repository from GitHub would display an empty list. Now, Open Remote Repository will list whatever resources RemoteHub can find given the permissions that the user has granted for that token.
2. We now display a warning instead of an error. I think a warning is better than an error here because an error implies that something went wrong, and presumably the user knew what permissions they were giving to VS Code.

![image](https://user-images.githubusercontent.com/30305945/153267525-ceb0d9dc-2fc6-489f-84c2-40110becd0d3.png)

However, there may still be room for improvement, because now the warning message goes away on its own after some time, and it's possible that a user gets stuck wondering why certain resources are not showing up. If this becomes a pain point for users, I can add a status bar item that says 'SSO to show more resources' or 'SSO required', though I don't want to do that now because that might clutter the status bar. @TylerLeonhardt, have we ever considered adding support for SSO in the Accounts menu? It seems like a natural fit for RemoteHub to increment the badge with a request to SAML if we detect that certain resources cannot be displayed given the user's current permissions.

**Comment by joyceerhl** [comment]
Latest update on this experience: instead of displaying a popup, we now display a quickpick item giving the user the option to single sign-on. 
  
![image](https://user-images.githubusercontent.com/30305945/155232082-98cd35b0-412e-4650-bd69-58fd0f4e26c4.png)

The quickpick stays open while you SSO. After authorizing additional organizations through the browser auth flow, you're taken back to VS Code and the quickpick list refreshes in-place with the new repos. This is the current expected experience:

https://user-images.githubusercontent.com/30305945/155232670-99ff7c35-7e2e-4b94-af83-093c31ffef02.mp4

The 'Open Pull Request from GitHub' option had the same issues, so I implemented the new SSO flow for PRs as well.

**Comment by joyceerhl** [comment]
For verification: sign out of GitHub.com, sign back in, do not authorize access to Microsoft, access vscode.dev, sign out of GitHub in the accounts menu, click Open Remote Repository in the remote indicator, click Open Repository from GitHub or Open Pull Request from GitHub. Verify there is no popup in the bottom right corner and you have the option to SAML in the quickpick.

**Comment by rzhao271** [comment]
After step 8, I don't see the Microsoft resources appear in the quickpick list, but they do show up after I search up `microsoft/`.
I don't see a popup during step 8, though. There is at most the "signed out" popup from step 5.

**Comment by joyceerhl** [comment]
@rzhao271 Did you see a SAML item in the quickpick list? And after SAMLing did you see microsoft/* resources in the quickpick when scrolling?

**Comment by rzhao271** [comment]
I see the following options for the quickpick:
![Step 7 quickpick](https://user-images.githubusercontent.com/7199958/156077243-f39de366-6dad-4918-a9a0-886d7e984190.PNG)
After authorizing Microsoft, I still only see `rzhao271/*` resources when scrolling, and have to search for the Microsoft ones.

**Comment by rzhao271** [comment]
Also, if I press cancel, then I get an infinite loading quickpick when it tries listing out the repositories. I then press the back button and get to the view above. If I then try pressing the "Open Repository from GitHub" option again, it is as though it remembered that I cancelled last time, and goes back to an infinite loading quickpick.

**Comment by joyceerhl** [comment]
> if I press cancel during the popup, then I get an infinite loading quickpick

Is this referring to https://github.com/microsoft/vscode-remotehub/issues/248?

That screenshot above is the first step of the quickpick--what do you see on the second step before you grant access to the Microsoft organization? To clarify, the popup that verification step 8 refers to is this one https://github.com/microsoft/vscode-remote-repositories-github/issues/113#issuecomment-1034086685

**Comment by rzhao271** [comment]
Yep. Looks like Issue 248 covers the infinite quickpick.
Before I grant access to the organization, I see the option to open a GitHub repository, a GitHub PR, or an Azure DevOps repo, I believe it was. I'm not sure what the expected items are.

**Comment by joyceerhl** [comment]
Ah sorry, my repro steps were not complete. They should be:

1. sign out of GitHub.com
2. sign back in
3. do not authorize access to Microsoft
4. access vscode.dev
5. sign out of GitHub in the VS Code accounts menu
6. _**sign into GitHub in the VS Code accounts menu, do not authorize access to Microsoft**_
7. click Open Remote Repository in the remote indicator
8. click Open Repository from GitHub or Open Pull Request from GitHub
9. verify there is no popup in the bottom right corner and you have the option to SAML in the quickpick, and after SAMLing your Microsoft resources now appear in the quickpick list
