### ISSUE TITLE
Explore clarifying that remote repository has uncommitted changes on entry and exit

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-remote-repositories-github#115]
Problem
1. User makes edits in github.dev via RemoteHub without committing.
2. Time passes. Repository is modified by current user or other collaborators
3. User goes to github.com and hits . to open in github.dev.
4. User is confused that repository doesn't reflect latest state of repository that they were just looking at in the github.com UI.

User may or may not notice that there are uncommitted changes and may or may not know that uncommitted changes prevent syncing with the remote.

Ideas
- When a user reenters a workspace with uncommitted changes, tell them they have uncommitted changes from a prior edit session (can surface "last edited" timestamps that we already show in the Remote Explorer) and that they must revert or commit their changes in order to sync with the remote
- When a user tries to close the tab without committing changes, display a dialog (consider using `onWillDisposeWorkbench.runCommands`) that displays a custom modal (Ben or Deepak may know more). We already do a blocking native dialog when the user does Ctrl+W (which normally closes the active editor but in web closes the tab). At minimum the dialog we display here must have a Don't Show Again option
    ![image](https://user-images.githubusercontent.com/30305945/152235697-c18eb50c-472a-485a-af5d-f73b916724c2.png)

**Comment by joyceerhl** [comment]
Quick prototype of what a dialog approach to this problem might look like when entering a workspace containing uncommitted changes:

![image](https://user-images.githubusercontent.com/30305945/156463127-943b9833-ff26-4f93-9f87-ab2365d3b309.png)

![image](https://user-images.githubusercontent.com/30305945/156467110-c6818f69-6c86-425b-9e35-b924b2e4a3d9.png)

**Comment by joyceerhl** [comment]
Current behavior:
- If there are no uncommitted changes, RemoteHub always shows you the latest version of a branch
- We fetch, not sync, if there are uncommitted changes

Papercuts/hypotheses:
- Users don't notice that there are uncommitted changes
- Users are surprised that uncommitted changes are persisted
- Users are surprised that uncommitted changes prevent automatic sync

Related prior art:
- `git.autoStash` setting in desktop which automatically stashes working changes when pulling
   ![image](https://user-images.githubusercontent.com/30305945/157477436-904f0929-b4e7-4c52-8709-bf4ba9620c11.png)

- GitHub.com PR UI stale indicator
   ![image](https://user-images.githubusercontent.com/30305945/157477035-8ec32707-bd84-4160-8caa-0d417a59f194.png)

-------------------------

Ideas so far:
1. Modal dialog to explain the connection between uncommitted changes and syncing
   ![image](https://user-images.githubusercontent.com/30305945/156463127-943b9833-ff26-4f93-9f87-ab2365d3b309.png)
   ![image](https://user-images.githubusercontent.com/30305945/157479312-2ca71a06-1168-4216-b247-d8788f0ea42c.png)

2. Setting to configure auto-syncing if there won't be conflicts with incoming changes + notification <-- issue with this approach is that the notification will likely get lost
    ![image](https://user-images.githubusercontent.com/30305945/157475698-0219d6a8-b490-4eb3-9390-b9e728f23511.png)
    ![image](https://user-images.githubusercontent.com/30305945/157478194-eaf153da-b405-40e4-a0a4-75cf9ee967aa.png)

3. A consolidated setting which prompts if not configured to auto-sync
    ![image](https://user-images.githubusercontent.com/30305945/157471813-73a17b27-93ea-4c1a-85d0-7df961b2f64f.png)
    ![image](https://user-images.githubusercontent.com/30305945/157473672-1848f8d5-bd70-4b60-adb1-b2cc89e8e524.png)

-------------------------

Outstanding issues/questions:
- Is it accurate to assume that users on github.dev/vscode.dev always want to see the latest version of their branch ('Always Autosync' option)?
- What should happen if the sync will result in merge conflicts? --> abort or attempt merge? Should this also be configurable or is that too complicated?
- Is this dialog useful enough to warrant its obtrusiveness?
- Are there other ways that we can either explain the connection between uncommitted changes and auto syncing through UI indicators (similar to what GitHub.com does with the 'Refresh' button on stale PRs), or improve the default behavior?
- Do we consider something drastic like making github.dev a truly ephemeral editor where uncommitted changes aren't persisted after navigating away, similar to how github.com behaves?

**Comment by joyceerhl** [comment]
@bpasero do you have any recommendations for how RemoteHub can reliably display a dialog when the user is about to navigate away from a repo with uncommitted changes? 

Based on @sandy081's suggestion at UX sync yesterday, I looked into whether we can display a warning before the user leaves a page containing uncommitted changes. Something like this in vscode.dev when the user navigates away, so that uncommitted changes are not abandoned:
![image](https://user-images.githubusercontent.com/30305945/157717389-ddbc3ea7-89ab-4c82-85b9-a1fd36850f7c.png)

Implementation above is done by registering a command in RemoteHub to display a prompt when there are uncommitted changes, and then including it as a command to run before page unload using the embedder's `onWillDisposeWorkbench` API
```ts
		const onWillDisposeWorkbench: IPreWorkbenchDisposalActions = {
			runCommands: [{ command: 'remoteHub.uncommittedChangesPrompt', args: [] }],
		};

```

Sadly it seems like we are limited by the browser's APIs here: https://developer.mozilla.org/en-US/docs/Web/API/Window/beforeunload_event This approach would result in us displaying two dialogs--one from RemoteHub with a detailed message about uncommitted changes, and one generic one from the browser with a non-configurable message that contradicts what the RemoteHub dialog says. :( 

In addition it seems that
1. `beforeunload` handler is not invoked when the user closes the browser tab by clicking x, or when the user navigates away by changing the url in the url bar. It's only invoked on ctrl+w for example, so this really doesn't help much
2. It is sometimes invoked when the user refreshes the page but not always. The docs do mention that the `beforeunload` event is not reliably fired
3. Not sure if the `beforeunload` handler can be made async--right now I can only get it to appear by hitting ctrl+w > Leave Site? dialog appears > select Cancel

**Comment by bpasero** [comment]
@joyceerhl in short: there is absolutely nothing we can do:
* you cannot alter the UI that shows when leaving a page
* you cannot run long running operations
* you cannot force prevent the user from leaving a page
* you cannot even know how much time you get to perform something when the user leaves

In long: https://github.com/MicrosoftEdge/MSEdgeExplainers/issues/147

**Comment by bpasero** [comment]
To give a bit more context: VSCode allows participants to participate in the shutdown phase (via `ILifecyclePhase`) and on desktop we can support all of it:
* long running operations
* custom dialogs
* blocking the shutdown until everyone participated
* even block the shutdown in case of error

When we ported VSCode to the web we had to drop all of that and limit it to a single veto from the `beforeUnload` handler which has the issues outlined in my first comment.

A few examples:
* a pending not-finished save will veto the unload
* a pending not-finished backup will veto the unload

To mitigate some of it, UI state is written to IndexedDB every 10 seconds (I know, ugly) to make sure that any accumulated UI state is not lost when leaving the app.

The answer from browser vendors so far has been to either:
* use a `ServiceWorker` that can continue to run in the background even after page unload
* "rescue" any data over to a public endpoint via [`sendBeacon`](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/sendBeacon) API which afaik is guaranteed to finish on unload

**Comment by joyceerhl** [comment]
Yeah, this is unfortunate but it makes sense, and thank you for the context. Until this behavior changes, it seems that it's not feasible for RemoteHub to clarify what happens to uncommitted changes on exit. 

In that case I think it's viable to pursue clarifying that there are uncommitted changes which prevent us from syncing with the remote. The proposal here is a dialog shown on entering a repo which is outdated, controlled by a setting `"remoteHub.experimental.uncommittedChangesOnEntry"`:
![image](https://user-images.githubusercontent.com/30305945/157771952-009d8405-d1e1-4bdc-a90c-15573292541a.png)
![Recording 2022-03-10 at 15 09 29](https://user-images.githubusercontent.com/30305945/157770523-913f32e6-52ea-45b7-b641-2627842efa42.gif)

I also briefly explored nudging the user to commit often, and clarifying that uncommitted changes are stored locally until the user commits since we've gotten [feedback](https://twitter.com/gvanrossum/status/1468385259637010433?s=12) that it's unclear where edits go. The prototype I showed of this is a setting `"remoteHub.commitOnSave"` which will commit the current file changes when the user hits Ctrl+S, with a default commit message like "Update {filename}". In order for this proposal to be viable we will need to ensure that this interacts well with the `"files.autoSave"` setting and that there aren't any performance issues. Maybe we can also explore unifying this auto-commit behavior with the `"editor.codeActionsOnSave"` setting.

**Comment by joyceerhl** [comment]
After selfhosting the uncommitted changes prompt without issues since last Friday, I've pushed a change to enable it in tonight's pre-release RemoteHub (therefore also insiders.vscode.dev). I added a Don't Show Again action to the dialog so that users can easily disable it if they don't find it helpful. Feedback is very welcome.

**Comment by joyceerhl** [comment]
Closing this out as the modal dialog is now enabled in pre-releases by default and I've tweaked it based on feedback from the team.
