### ISSUE TITLE
Azure Repos Write Support

### ISSUE THREAD

**Issue by davidcorrigan714** [microsoft/vscode-remote-repositories-github#117]
Looks like Azure Repos is still in read only mode. Is there an ETA on write support? The initial announcement for vscode.dev implied it was in active development and I've been eager to try it out as I do a lot of development in Azure DevOps but I haven't been able to find any information or Issue tracking that feature.

**Comment by joyceerhl** [comment]
@davidcorrigan714 We're actively working on it--@lszomoru can provide more information.

**Comment by lszomoru** [comment]
This morning we have updated https://insiders.vscode.dev with the latest version of the Azure Repos extension which contains a new experimental setting, `"azureRepos.experimental.writeSupport": true`, to enable write support for Azure Repos. Please use the setting to enable write support, and let us know if you are running into any issues. Thanks!

**Comment by lszomoru** [comment]
The current plan is to enable write support in the next release of the extension.
