### ISSUE TITLE
RemoteHub-contributed colors are not correctly applied when used in file decoration provider

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-remote-repositories-github#119]
![image](https://user-images.githubusercontent.com/30305945/153308156-197a2492-0c3a-472e-90cc-f1ddcfada2de.png)

**Comment by joyceerhl** [comment]
@jrieken git blame in microsoft/vscode suggests you might own the file decoration provider, please let me know if I am mistaken. For some reason decorations are only applied if the color IDs contain zero or one `.`s. So theme colors work if the name is `foobar` or `foo.bar`, but decorations stop being applied for `foo.bar.baz`. With this workaround in RemoteHub:

![image](https://user-images.githubusercontent.com/30305945/153309963-7779a0f7-9ec2-46db-b08a-a06b8c971288.png)

I am pretty sure that this used to work, but if this is just a constraint of the color contribution point, could we update the documentation to include that please?

**Comment by jrieken** [comment]
Nice catch! This is actually an issue with how color ids are translated into css variables: https://github.com/microsoft/vscode/blob/4a130c40ed876644ed8af2943809d08221375408/src/vs/platform/theme/common/colorRegistry.ts#L35 uses `replace`, not replaceAll 🤦
