### ISSUE TITLE
SCM input validation message 'Don't Show Again' command link does nothing

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-remote-repositories-github#120]
Clicking 'Don't Show Again' should run a RemoteHub command to toggle a setting value, but currently clicking it only dismisses the validation message. We are setting `isTrusted: true` on the `MarkdownString`.

**Comment by joyceerhl** [comment]
@lszomoru Do you have any context on how command links are handled in the SCM input box validation messages?

**Comment by lszomoru** [comment]
@joyceerhl, I do not, though I do not believe that anything changed in SCM related to this. We can take a look together.

**Comment by joyceerhl** [comment]
This was caused by an upstream change to markdown link rendering in VS Code itself and has been fixed since several releases ago.
