### ISSUE TITLE
Add ability to Stage Changes for resources in Merge Conflicts resource state

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-remote-repositories-github#125]
With the previous simplified merge, resources in the Merge Conflicts resource group had a simplified 'Keep Changes' command contributed inline in the SCM context menu which simply kept your local changes and discarded all incoming changes. This worked because the simplified merge strips out the incoming changes from the file content such that your local changes 'always win'. Since the file contents are already updated to be your local changes, clicking 'Keep Changes' merely marks the file as without conflicts in internal state.

The 'Keep Changes' command does not work with the new merge conflict UX because the file contents are now the merged contents which may contain conflict markers that need to be resolved. Additionally, we use the + icon for 'Keep Changes', which may surprise users who are coming from desktop and expect the 'Stage Changes' behavior. Since 'Keep Changes' does not work with the new merge experience, I have enabled it only when `remoteHub.experimental.useSimplifiedMerge` is `true`.

Instead we should implement a desktop git-like 'Stage Changes' command when using the new merge conflict UX. If the user tries to stage a file containing conflicts, the user should be prompted to resolve conflicts, and then the changestore should be updated to reflect the resolved file contents.

**Comment by rchiodo** [comment]
@joyceerhl can you add some verification steps? Thanks.

**Comment by joyceerhl** [comment]
1. Introduce a merge conflict in a repo in insiders.vscode.dev. For example, create a private repo and edit the same line in the same file, or create the same file with conflicting contents, from both github.dev and insiders.vscode.dev. Commit the changes from github.dev, then try to sync from insiders.vscode.dev
2. The changed file should end up in the Merge Conflicts resource group in the source control view
3. There should be a + icon. Ensure the tooltip reads Stage Changes instead of Keep Changes
4. Ensure that you can click this to stage the file
5. If the conflict is a Deleted by Them or Deleted by Us change, ensure that you are able to stage the change, and that you get prompted the way you do on desktop VS Code for which file's contents to keep

**Comment by rchiodo** [comment]
Delete doesn't seem to be working? 
- Create private branch and open in github.dev and insiders.vscode.dev
- Edit file in github.dev and submit
- Refresh insiders.vscode.dev (see the edit)
- Edit file in both
- Submit in github.dev
- Refresh insiders.vscode.dev - shows merge conflict
- Delete file in github.dev and submit
- Refresh insiders.vscode.dev - STILL shows merge conflict and nothing about delete

Additionally I don't see merge conflict markers, I instead get a diff editor. Maybe that's on purpose.

**Comment by rchiodo** [comment]
No sorry wait, I 'refreshed' incorrectly. I hit the 'refresh' button. I didn't pull.

**Comment by rchiodo** [comment]
Okay if I pull, the merge conflict markers show up correctly but delete still doesn't work.

So repro steps:

Delete doesn't seem to be working?

- Create private branch and open in github.dev and insiders.vscode.dev
- Edit file in github.dev and submit
- Pull insiders.vscode.dev (see the edit)
- Edit file in both
- Submit in github.dev
- Pull insiders.vscode.dev - shows merge conflict
- Delete file in github.dev and submit
- Pull insiders.vscode.dev - delete conflict not shown

**Comment by joyceerhl** [comment]
Hmm, followed your steps but I do get the delete conflict (see the 'Deleted by Incoming' tooltip):

![image](https://user-images.githubusercontent.com/30305945/155429459-c07dd645-6356-439d-a692-4e73ef4cec93.png)

**Comment by rchiodo** [comment]
Mine is showing this? 

![image](https://user-images.githubusercontent.com/19672699/155429620-925a30ba-aeb3-4263-bf3d-519f1c78a554.png)


Maybe I don't have the right extension installed?

**Comment by rchiodo** [comment]
Oh I guess github remote is part of insiders.vscode.dev. Not an extension

**Comment by joyceerhl** [comment]
The extension is bundled as a builtin extension in insiders.vscode.dev, so you shouldn't need to install anything special. On desktop though you do need to install it separately.

> Pull insiders.vscode.dev - shows merge conflict

After this step, do you resolve the merge conflicts, delete the file from github.dev, then sync? Would you mind sharing a recording so I can see how you got into that state?

**Comment by rchiodo** [comment]
Never mind, I'm an idiot. I deleted the wrong file. 

I thought I had deleted README.md but it was requirements.txt:

https://github.com/rchiodo/vscode-python/commit/0336d71fb5a88b8be21e03c47a5dca6f26fb7dfd

**Comment by rchiodo** [comment]
When I deleted README.md, I got the delete notification in merge conflicts list

**Comment by rchiodo** [comment]
Sorry for the run around.

**Comment by joyceerhl** [comment]
Thank you for the thorough testing! 

> I deleted the wrong file.

Story of my life this iteration :)
