### ISSUE TITLE
Unable to sync when incoming and current changes add the same file

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-remote-repositories-github#127]
1. Across vscode.dev and github.dev, create the same file e.g. foo.md in a repo with conflicting changes
2. Commit in vscode.dev
3. Sync from github.dev and accept syncing with potential conflicts. What _should_ happen is that RemoteHub presents this as an Added By Both conflict in the SCM view
4. 🐛 unable to sync
 
This is because when performing the three way merge as part of the sync process, we attempt a `workspace.fs.readFile` on the provider URI representing the base change, but at that point the file doesn't exist, so the `readFile` call throws and the entire merge/sync is aborted

**Comment by joyceerhl** [comment]
Note, this will not repro if using RemoteHub stable, because https://github.com/microsoft/vscode-remote-repositories-github/issues/126 obscures this bug by not flagging that two files have potential conflicts. You will need to use RemoteHub pre-release e.g. v0.25.2022021509 which contains the fix for #126 but not the fix for this issue.

**Comment by meganrogge** [comment]
I expected the hover of this decoration to provide action(s) I can take. Instead, I have to notice this in the status bar. 
![Screen Shot 2022-02-25 at 12 27 11 PM](https://user-images.githubusercontent.com/29464607/155768176-989e1659-7251-4b03-bef2-cf50181c9769.png)
![Screen Shot 2022-02-25 at 12 28 47 PM](https://user-images.githubusercontent.com/29464607/155768389-d1a81b34-1d0d-4567-a709-1e7e34cc17e7.png)
