### ISSUE TITLE
Provide a way to add a new GitHub repository from the Remote Explorer view

### ISSUE THREAD

**Issue by adriancuadrado** [microsoft/vscode-remote-repositories-github#139]
In the Remote Explorer I don't see any option anywhere to open another GitHub repository once one is opened.

![image](https://user-images.githubusercontent.com/29214635/155898719-36bf920d-a429-4151-9c09-469b9f0d4c77.png)

The "Remote - SSH" and "Remote - WSL" extensions are visually very similar, but they do include a button to add SSH and WSL targets:

![image](https://user-images.githubusercontent.com/29214635/155898858-8c83336e-cbd4-4e7f-b7a7-d3a2e09e057e.png)

**Comment by joyceerhl** [comment]
Another way to change GitHub repositories without the command palette: you can click on the Remote Indicator in the bottom left corner and select 'Open Remote Repository' from the quickpick to switch to another GitHub repository.

![image](https://user-images.githubusercontent.com/30305945/156031103-98694b81-2351-4879-afcb-34a26fd25195.png)

👍 good point on aligning with other contributions to the Remote Explorer view.
1. Containers has 'New Container' 
    ![image](https://user-images.githubusercontent.com/30305945/156031470-f49090a8-bb52-46c6-8ac2-29f3f24b062c.png)
2. SSH has 'Add New'
    ![image](https://user-images.githubusercontent.com/30305945/156031548-0f978370-ce2b-4370-9c3f-c58427d57131.png)
3. WSL has 'Add a Distro'
    ![image](https://user-images.githubusercontent.com/30305945/156031608-eb3d6da5-1306-4c6d-afe9-15140e16f105.png)

**Comment by JeroenHeemskerk** [comment]
The "+" of "add" button is one I really mis aswell
