### ISSUE TITLE
No back button after selecting 'Open Repository from Azure Repos'

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-remote-repositories-github#141]
This is what I get after selecting 'Open Repository from GitHub':
![image](https://user-images.githubusercontent.com/30305945/156213097-d8a2378e-ede7-4591-9772-47b7d1dfe837.png)

This is what I get after selecting 'Open Repository from Azure Repos':
![image](https://user-images.githubusercontent.com/30305945/156213109-9b02745f-18f6-4fc2-bde2-765755c95322.png)

Would be great to have consistency and also to support the ability to go back to the org selection step from the project selection step.

**Comment by lszomoru** [comment]
Closing in favour of https://github.com/microsoft/vscode-remote-repositories-github/issues/399
