### ISSUE TITLE
Disallow pull/sync when there are unresolved merge conflicts

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-remote-repositories-github#146]
This currently doesn't behave well. On desktop git disallows this:

```
error: Pulling is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit.
fatal: Exiting because of an unresolved conflict.
```

**Comment by Tyriar** [comment]
I checked out a PR with conflicts and ran the `Remote Repositories: Sync (Pull & Push)` command. There were no errors but there was also zero feedback good or bad. Would it be possible to disable the command all together if there are conflicts via a context key?

**Comment by roblourens** [comment]
It seems like this isn't working for me. Nothing prevents me from pulling into a workspace with a merge conflict. Once I do, I get a merge conflict on the merge markers

![image](https://user-images.githubusercontent.com/323878/160198886-5aee326c-017c-466d-8fa8-eea45b938fe2.png)

Here I pulled once while already having a conflict, and here is the dialog when I start to pull again (using the sync icon or Pull in the command palette)

**Comment by roblourens** [comment]
Oh, I had this tab open from this morning and didn't even see @Tyriar's comment

**Comment by joyceerhl** [comment]
Are y'all using pre-release RemoteHub (bundled by default on insiders.vscode.dev, but not on github.dev)? This seems to work as expected for me using the Pull / Sync command palette commands, status bar sync icon, or SCM pull command:
![image](https://user-images.githubusercontent.com/30305945/160200088-a01dcfb7-04a6-4d87-8bee-8fcbc8c5a34d.png)

**Comment by roblourens** [comment]
Oh, that's my problem 😁
