### ISSUE TITLE
Empty selection following "Open Repository from GitHub"

### ISSUE THREAD

**Issue by zivcaspi** [microsoft/vscode-remote-repositories-github#15]
It's hard to describe the problem any more -- following the first-time authentication, and having validated (through "Manage Trusted Extensions") that I'm signed-in and "Remove Repositories" can use that account, the list of repositories I'm presented with for GitHub is completely empty. No error is offered or any indication of other failure.

**Comment by eamodio** [comment]
So when you run _Open Repository..._ and choose _Open Repository from GitHub_ you don't see any repositories by default? If you start typing do you see any?

**Comment by zivcaspi** [comment]
Correct -- It's empty when it first opens, and remains empty even if I type stuff

**Comment by eamodio** [comment]
Please enable output channel logging by running from _Remote Repositories: Enable Debug Logging_ from the command palette (`ctrl+shift+p` or `cmd+shift+p`). This will enable logging to the _Remote Repositories_ channel in the _Output_ pane.

Once enabled, please reproduce the issue, and attach the log from the _Remote Repositories_ channel.

**Comment by zivcaspi** [comment]
Unfortunately, seems like there's no such command. I'm getting the following error:

```
Command 'Remote Repositories: Enable Debug Logging' resulted in an error (command 'remoteHub.enableDebugLogging' not found)
```

This is Remote Repositories version v0.10.1.

**Comment by eamodio** [comment]
There is an issue where that command won't activate the extension -- if you run _Remote Repositories: Open Repository..._ from the command palette first (that will cause the extension to activate), and then the debug logging command should work.

**Comment by craigktreasure** [comment]
I'm experiencing the same issue in v0.10.1. The debug logging doesn't include much after attempting to open a repository using "Remote Repositories: Open Repository..." and then "Open Repository from GitHub":
```
[2021-06-23 06:11:55:654] [    4] (A) Reader(3|WorkspaceRepositories) • WorkspaceRepositories.get
[2021-06-23 06:11:55:655] [    4] (L) Reader(3|WorkspaceRepositories) waited for 0 ms • WorkspaceRepositories.get
[2021-06-23 06:11:55:655] [    4] (U) Reader(3|WorkspaceRepositories) locked for 0 ms • WorkspaceRepositories.get
```

![image](https://user-images.githubusercontent.com/6309423/123045633-fd756980-d3af-11eb-8be8-0c33e7d8a26d.png)

**Comment by eamodio** [comment]
Can you try to see if the issue is still reproducible in the Remote Repositories (Insiders) edition?

You can install the Remote Repositories (Insiders) edition from [here](https://marketplace.visualstudio.com/items?itemName=GitHub.remotehub-insiders). 

Please be sure you are using the Insiders edition of VS Code, and to disable or uninstall the stable version of Remote Repositories first. Also note, that no data is shared between the insiders and stable editions.

**Comment by zivcaspi** [comment]
Thanks, it does work with the Remote Repositories (Insiders) build!
