### ISSUE TITLE
Rename `Commit` to `Commit and Push`

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-remote-repositories-github#151]
On desktop, committing and pushing are separate operations. In RemoteHub they are an atomic operation. We should make the `remoteHub.commit` command name and tooltip reflect this, so that users aren't left wondering how to push after committing like in https://github.com/microsoft/vscode-remote-repositories-github/issues/148. @KartikM123 suggested changing the tooltip to read 'Commit and Push' instead of 'Commit'.

**Comment by mjbvz** [comment]
Hm, I'm still seeing this with v0.26.0 of the `GitHub Repositories` extension. Does a new extension version need to be published?

**Comment by joyceerhl** [comment]
insiders.vscode.dev should have `v0.27.2022032303` 🤔

**Comment by mjbvz** [comment]
Ok on GitHub.dev with insiders I still get 0.26

I confirmed it on vscode.dev insiders though

**Comment by joyceerhl** [comment]
Yeah GitHub.dev does not bundle pre-releases of builtin extensions based on VS Code quality, so that is expected behavior. Thanks for checking!
