### ISSUE TITLE
Improve suggestion to index the remote repository

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode-remote-repositories-github#17]
From https://github.com/microsoft/vscode-remotehub/issues/79#issuecomment-831570019: 

![image](https://user-images.githubusercontent.com/35271042/116940265-8e3a8f00-ac22-11eb-848d-89b674d27103.png)

![image](https://user-images.githubusercontent.com/35271042/116940277-90045280-ac22-11eb-8768-83b1057dc758.png)

Based on discussion in https://github.com/microsoft/vscode-dev/issues/128, I think makes sense to use above styling, with wording like:

1. For exact text searches, [enable indexing]

cc @bamurtaugh

**Comment by bamurtaugh** [comment]
The styling and wording makes sense to me!

**Comment by JacksonKearl** [comment]
![image](https://user-images.githubusercontent.com/8586769/122487188-83984700-cf8f-11eb-81e6-b2082acb4a04.png)
