### ISSUE TITLE
Text search on a fork with fewer stars than upstream fails silently

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-remote-repositories-github#173]
Feedback from https://twitter.com/nthonyChu/status/1505036135315124225. Searching on https://insiders.vscode.dev/github/microsoft/azure-docs with repository indexes disabled yields no results. This is due to GitHub API limitations, but we should surface this with a warning instead of silently returning no results. 

We have something similar for Azure Repos search when you're searching on a non-default branch that hasn't been configured for code search.
![image](https://user-images.githubusercontent.com/30305945/159994790-f02faa42-b47c-4feb-bffb-ded7c95ca6a7.png)

**Comment by JacksonKearl** [comment]
GitHub API just gives back an empty array, no error signaling as far as I can tell:
```
➜  ~ curl 'https://api.github.com/search/code?q=boop%20repo%3Amicrosoft%2Fazure-docs'  
{
  "total_count": 0,
  "incomplete_results": false,
  "items": [

  ]
}
```

So not sure how we'd go about detecting this case.

**Comment by joyceerhl** [comment]
There's nothing we can do about this at the moment. We can revisit this once the new code search becomes available via API. https://github.com/features/code-search
