### ISSUE TITLE
`experimental.fs.useTars` ignored when set to 'never' 

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-remote-repositories-github#179]
1. Set `experimental.fs.useTars` to 'never', reload
2. Open a file in github.dev
3. Open GitHub Repositories output channel
4. :bug: see messages about getting tar files

**Comment by joyceerhl** [comment]
Verification steps: do the repro steps in insiders.vscode.dev, you should not see messages about getting tar files.

**Comment by rzhao271** [comment]
I can't seem to repro the issue even using stable github.dev.

**Comment by joyceerhl** [comment]
Sorry, this only crops up on PRs. Just verified it still repros for me in github.dev with `https://github.dev/microsoft/vscode/pull/148732` and is fixed in `https://insiders.vscode.dev/github/microsoft/vscode/pull/148732`. 
![image](https://user-images.githubusercontent.com/30305945/166832903-f14b9fe0-012e-40f1-b70d-c5ae31197ffe.png)

Would you mind trying again @rzhao271 please?
