### ISSUE TITLE
how to delete files or folders ?

### ISSUE THREAD

**Issue by lehaifeng000** [microsoft/vscode-remote-repositories-github#18]
when i try to delete some files, it remind me as follow image. i use macos11.3
![image](https://user-images.githubusercontent.com/29175644/122151762-b01a6900-ce92-11eb-89f2-698a41f0157d.png)

**Comment by eamodio** [comment]
This has been resolved in the latest Remote Repositories insiders edition.

If you want to verify this fix, you can install the Remote Repositories insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=GitHub.remotehub-insiders).

Please be sure to disable or uninstall the stable version of Remote Repositories first. Also note, that no data is shared between the insiders and stable editions.
