### ISSUE TITLE
No organisations listed for Azure DevOps Repos

### ISSUE THREAD

**Issue by Reinachan** [microsoft/vscode-remote-repositories-github#183]
Whenever I attempt to browse to an Azure DevOps repository with the Remote Repository and Azure Repos plugins, I'm stuck at the page where you have to pick an organisation.

![image](https://user-images.githubusercontent.com/16106839/161780173-87a2044f-9505-4f3d-bcdf-d93dda11950f.png)

I assume this issue is related to how the company I'm employed at handles users. We have a single Microsoft account for signing in, but for Azure services, there are two different domains (the Azure Account plugin call these Tenants) that I have a user on and only one of them have access to the DevOps repos.

(I've removed any personal info from this, it's just for demonstration)
![image](https://user-images.githubusercontent.com/16106839/161783660-7edb58bb-997e-4a62-876f-f69c28a12228.png)

Either the method of switching between domains (Tenants) should be better documented, or functionality to choose domain (Tenant) should be added.

**Comment by joyceerhl** [comment]
@reinachan can you share the output logs when you set `"azureRepos.logLevel": "debug"` in your settings.json file, reattempt opening the picker, and then inspect the Azure Repos output channel?
![image](https://user-images.githubusercontent.com/30305945/161789853-f4a7335d-20fe-4f19-bcbf-c8288f256e87.png)

**Comment by Reinachan** [comment]
> @Reinachan can you share the output logs when you set `"azureRepos.logLevel": "debug"` in your settings.json file, reattempt opening the picker, and then inspect the Azure Repos output channel?

Yes, here you go @joyceerhl 
```
[2022-04-05 15:35:19:975] [    2] ChangeStore.getWorkspacesWithChanges()
[2022-04-05 15:35:19:975] [    2] ChangeStore.getWorkspacesWithChanges() took 0 ms
[2022-04-05 15:35:19:988] [    3] (A) Reader(1|WorkspaceRepositories) • WorkspaceRepositories.get
[2022-04-05 15:35:19:988] [    3] (L) Reader(1|WorkspaceRepositories) waited for 0 ms • WorkspaceRepositories.get
[2022-04-05 15:35:19:988] [    4] MementoStorage.get(workspaceRepositories): scopedKey=workspaceRepositories
[2022-04-05 15:35:19:988] [    4] MementoStorage.get(workspaceRepositories): scopedKey=workspaceRepositories took 0 ms
[2022-04-05 15:35:19:988] [    3] (U) Reader(1|WorkspaceRepositories) locked for 0 ms • WorkspaceRepositories.get
[2022-04-05 15:35:22:960] [    5] AzDO.ensureAuthenticated
[2022-04-05 15:35:23:009] [    5] AzDO.ensureAuthenticated took 48 ms
```

**Comment by etiennejcharles** [comment]
> > @Reinachan can you share the output logs when you set `"azureRepos.logLevel": "debug"` in your settings.json file, reattempt opening the picker, and then inspect the Azure Repos output channel?
> 
> Yes, here you go @joyceerhl
> 
> ```
> [2022-04-05 15:35:19:975] [    2] ChangeStore.getWorkspacesWithChanges()
> [2022-04-05 15:35:19:975] [    2] ChangeStore.getWorkspacesWithChanges() took 0 ms
> [2022-04-05 15:35:19:988] [    3] (A) Reader(1|WorkspaceRepositories) • WorkspaceRepositories.get
> [2022-04-05 15:35:19:988] [    3] (L) Reader(1|WorkspaceRepositories) waited for 0 ms • WorkspaceRepositories.get
> [2022-04-05 15:35:19:988] [    4] MementoStorage.get(workspaceRepositories): scopedKey=workspaceRepositories
> [2022-04-05 15:35:19:988] [    4] MementoStorage.get(workspaceRepositories): scopedKey=workspaceRepositories took 0 ms
> [2022-04-05 15:35:19:988] [    3] (U) Reader(1|WorkspaceRepositories) locked for 0 ms • WorkspaceRepositories.get
> [2022-04-05 15:35:22:960] [    5] AzDO.ensureAuthenticated
> [2022-04-05 15:35:23:009] [    5] AzDO.ensureAuthenticated took 48 ms
> ```

Got the exact same issue, let me know if I can help in any way

**Comment by lszomoru** [comment]
Could you please confirm that you are signed into VS Code using the Microsoft account that has access to the Azure DevOps organisations? Could you try to sign out from the Microsoft account, and attempt to go through the flow to open an Azure Repos repository? If you open the Developer Tools using the `Developer: Toggle Developer Tools` command, do you see any related errors there? 

Here is another thing that we can try in order to better understand what is returned by Azure DevOps:
1. Open a browser window and navigate to https://insiders.vscode.dev/
2. Open the developer tools in the browser and switch to the "Network" tab
3. Now try to open a repository hosted on Azure Repos, you should see request being made in the "Network" tab 
4. There should be *two* request that starts with `accounts?`
5. Can you please click on each, then click on the "Preview" tab to see the responses of each
    - Can you see the requests returning any JSON payload containing a list of the Azure DevOps organisations?

**Comment by Reinachan** [comment]
@lszomoru Sorry for the delayed response.

> Could you please confirm that you are signed into VS Code using the Microsoft account that has access to the Azure DevOps organisations? 

I'm using the OAuth flow to sign in using the same Microsoft account that I use to sign into the `dev.azure.com/CompanyName`  which has access to the repositories. 

Keep in mind that there are two Azure domains or accounts or whatever associated with this Microsoft account login (what I mentioned above). One which service-desk controls and is used for Windows and internal company software, and another which has access to Azure services, Visual Studio, and has accounts in our development stuff. When I sign into each service, this is automatically resolved, so maybe this isn't of relevance to you.

> If you open the Developer Tools using the Developer: Toggle Developer Tools command, do you see any related errors there?

Signing out and then back into VSCode and then authenticating again with Azure Repos does not throw any errors in the developer console. The only errors I'm getting has to do with a missing favicon which I highly doubt is of relevance.

> Now try to open a repository hosted on Azure Repos, you should see request being made in the "Network" tab
There should be two request that starts with accounts?
Can you please click on each, then click on the "Preview" tab to see the responses of each
Can you see the requests returning any JSON payload containing a list of the Azure DevOps organisations?

The first of each is just an `options` request which returns nothing. I assume that's not relevant.

The get request for `/accounts?memberid=xxxxxxxxx?api-version=7.0` returns an empty list. The get request before that, `/me?api-version=7.0`, returns the correct email address and name at the very least.

accounts
![accounts query](https://user-images.githubusercontent.com/16106839/162719960-8fde0ffe-bdf2-4aaa-8699-65ddb0bc922f.png)

**Comment by lszomoru** [comment]
@Reinachan, thank you very much for the additional information. 

> Keep in mind that there are two Azure domains or accounts or whatever associated with this Microsoft account login (what I mentioned above). One which service-desk controls and is used for Windows and internal company software, and another which has access to Azure services, Visual Studio, and has accounts in our development stuff. When I sign into each service, this is automatically resolved, so maybe this isn't of relevance to you.

I do think that this might be relevant to the issue. Would it be possible for you to share the response that the `/me?api-version=7.0` returns? You can edit out all the sensitive information, as I am more curious about the shape of the response as well as a confirmation that the `publicAlias` property is set to a valid GUID. 

//cc @TylerLeonhardt

**Comment by Reinachan** [comment]
> Would it be possible for you to share the response that the /me?api-version=7.0 returns? You can edit out all the sensitive information, as I am more curious about the shape of the response as well as a confirmation that the publicAlias property is set to a valid GUID.
@lszomoru 

Sure, it returns this (with sensitive info blocked out ofc)
```json
{
	"displayName": "FirstName FamilyName",
	"publicAlias": "cb1979f0-cc54-632f-b796-0254e8f140ff",
	"emailAddress": "address@company.no",
	"coreRevision": 383493889,
	"timeStamp": "2022-02-25T14:04:49.49+00:00",
	"id": "cb1979f0-cc54-632f-b796-0254e8f140ff",
	"revision": 383493889
}
```

**Comment by Reinachan** [comment]
Any update on this? Do I still need to provide more info?

**Comment by lszomoru** [comment]
@TylerLeonhardt, any idea how we could further troubleshoot this?

**Comment by TylerLeonhardt** [comment]
Not sure... Can we get some Azure DevOps experts internally to chime in? I feel as if we made some assumptions that aren't valid in @Reinachan's case.

**Comment by worksofliam** [comment]
Having the exact same issue tonight. Unable to browse any repo from vscode.dev, and local, even after I signed into Azure DevOps. VS Code can see I am signed in, but no organisations are appearing.

**Comment by lszomoru** [comment]
We now support multiple Azure Active Directory tenants so this issue should be resolved.
I will go ahead and close this issue, but please feel free to reopen it in case you still experiencing this issue.
