### ISSUE TITLE
Continue On > Create New Codespace when viewing a PR from a fork fails

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-remote-repositories-github#185]
1. Open https://github.dev/microsoft/vscode/pull/144365
2. Click on the remote indicator in the bottom left
3. Click on the Continue On item 
4. Click on Create New Codespace
5. :bug: Creating Codespace fails

**Comment by joyceerhl** [comment]
Verification: try the repro steps in https://insiders.vscode.dev/github/microsoft/vscode/pull/146601 (ensure you do not have any pending updates for the Remote Repositories extension). Codespace creation should succeed

**Comment by rchiodo** [comment]
@joyceerhl I don't seem to get the codespace option? Do I need to sign up for something?

All I get is this if pick continue on:

![image](https://user-images.githubusercontent.com/19672699/165833963-0ad9fa6d-bbb7-4ae3-a193-3b909d6f33c1.png)

**Comment by joyceerhl** [comment]
@rebornix are you able to verify this? 

I'm not sure why the Codespaces option isn't showing up for @rchiodo, that seems like a bug in the Codespaces extension. Do you have the option to create a Codespace on GitHub.com?

**Comment by rebornix** [comment]
@joyceerhl is this an known issue that Codespace can't be installed on it? (I'm seeing the same as @rchiodo , no open in codespace)

<img width="265" alt="image" src="https://user-images.githubusercontent.com/876920/166499555-32337a33-4c4b-4e4d-8d74-9fc3d78a90e8.png">

**Comment by rebornix** [comment]
Tried to verify on github.dev but got this notification

<img width="647" alt="image" src="https://user-images.githubusercontent.com/876920/166499793-440445de-311f-4eb5-adef-832e5e150ea5.png">

Not sure what that means and how to proceed.
