### ISSUE TITLE
Remote Repositories should notify when using picker and GitHub Repositories is not installed

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode-remote-repositories-github#193]
Using the preview version v0.7.2022051001 of the remote repositories extension in Insiders on Mac

Version: 1.68.0-insider
Commit: dcf27391b7dd7c1cece483806af75b4f87188e70
Date: 2022-05-10T05:16:41.140Z
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Darwin x64 20.6.0

When I try to put in valid URL or browse to a repo on GitHub, I can't open the repository, nothing happens.

- Insiders, Mac
- Install preview version of remote repositories extension
- F1 > Remote Repositories: Open Remote Repository
- Type in https://github.com/microsoft/vscode
- Press Enter

Result: Quick Pick goes away, nothing else happens, repository is not opened

Similarly, if I browse my GitHub repos using the quick pick, when I press Enter to select a repo nothing happens, the Quick Pick does not go away.

I set `"remoteHub.logLevel": "debug"` and this is the output:

```
[2022-05-10 17:48:45:582] Running on the desktop; workspaceId=; storageUri=file:///Users/chris/Library/Application Support/Code - Insiders/User/globalStorage/ms-vscode.remote-repositories
[2022-05-10 17:48:45:652] [ GHPR] Registering...
[2022-05-10 17:48:45:653] [ GHPR] Registration complete
```

No errors in the dev tools console.

**Comment by joyceerhl** [comment]
Do you have GitHub Repositories installed? https://marketplace.visualstudio.com/items?itemName=GitHub.remotehub I just tried opening from a URL or selecting a repo and it seems to work for me.

**Comment by chrisdias** [comment]
ha, no i didn't, i was so accustomed to talking about the "remote repositories" extension that i just looked for that in the marketplace, instead of the GitHub repositories extension.  Once I installed the GitHub repos extension it started to work.

That said, what does this extension do without the GH or Azure Repos extensions installed?  Can we provide a prompt telling people they need to install another extension?

**Comment by joyceerhl** [comment]
Ah sorry about that, yeah we can definitely handle this better. If you have this extension installed but not GitHub Repositories / Azure Repos, and you already have a GitHub repo or Azure Repos repo open (e.g. from the recents list), then Remote Repositories will tell you to install the relevant extension. We should do the same thing when the user is going through the open picker.

**Comment by connor4312** [comment]
This works, though you shouldn't necessarily need to reload the window after installing it--it should be accessible shortly thereafter. In core when we install the hex editor to view memory, we don't need to reload and instead wait for it to appear in our extensions (the `getExtension` method in the vscode API might work similarly for this)

https://github.com/microsoft/vscode/blob/4017fd126ffb62def37c3bb380eb1a1866884ebe/src/vs/workbench/contrib/debug/browser/variablesView.ts#L541-L542
