### ISSUE TITLE
URL trigger for opening repo not working after version 0.26.0 in VS Code 

### ISSUE THREAD

**Issue by GrayGalaxy** [microsoft/vscode-remote-repositories-github#194]
I have a chrome extension [better-github](https://github.com/GrayGalaxy/better-github), one of the feature was to open a GitHub repo as remote-repository.

I first find out this through [this](https://chrome.google.com/webstore/detail/vscode-button/belghfhelimohhplefkfbphdobmenalo/related) extension.

![image](https://user-images.githubusercontent.com/49820575/168913474-4799b884-00a6-41c0-85dc-64f7fb4ec537.png)

The URL that can trigger is like this `vscode://github.remotehub/open?url=https://github.com/microsoft/vscode`. this should open a new instance of VS Code and connect to the repository.

But after **update v0.28.0** it seems be not working at all. The URL trigger is working fine with versions below v0.26.0.

I do not know if the protocol is changed or something else. Please guide me through this.

---
Current setup
VS Code: v1.67.1
OS: Windows

**Comment by joyceerhl** [comment]
Thanks for filing an issue. The uri handler has moved to `ms-vscode.remote-repositories`, so you would now want 

```
vscode://ms-vscode.remote-repositories/open?url=https://github.com/microsoft/vscode
```
Pushed a fix for this which should be available in tomorrow's pre-release of https://marketplace.visualstudio.com/items?itemName=ms-vscode.remote-repositories

**Comment by meganrogge** [comment]
Joyce I'm not seeing the repo open when I use the link you suggest above 
https://user-images.githubusercontent.com/29464607/171694552-6caa869a-f480-497e-b139-ca08d6d7e1da.mov

**Comment by joyceerhl** [comment]
🤔 what version of Remote Repositories do you have installed in VS Code stable?

**Comment by meganrogge** [comment]
Also switched to the pre-release version and it's not working with that either

**Comment by meganrogge** [comment]
Output:
![Screen Shot 2022-06-02 at 11 08 17 AM](https://user-images.githubusercontent.com/29464607/171697543-1756924d-7575-4970-93e2-3d290c2966fc.png)

**Comment by meganrogge** [comment]
No errors in the dev tools console

**Comment by joyceerhl** [comment]
Weird, works for me...do you have GitHub Repositories too?

**Comment by meganrogge** [comment]
![Screen Shot 2022-06-02 at 11 33 33 AM](https://user-images.githubusercontent.com/29464607/171701670-0063a516-8de5-45b1-af54-713fcf9c1497.png)

**Comment by meganrogge** [comment]
Also tried the pre-release version of that one

**Comment by meganrogge** [comment]
Didn't work at all for me yesterday, but I see the repo open correctly today
