### ISSUE TITLE
When opening the remote I would like to add an option to open in a new window.

### ISSUE THREAD

**Issue by ouweiya** [microsoft/vscode-remote-repositories-github#2]
When opening a remote I would like to add an option to open in a new window instead of the current window.

![image](https://user-images.githubusercontent.com/28357731/121625324-d52f6600-caa5-11eb-9e9e-c0f27e85ee1f.png)

I know that in Remote Manager, you can use the Alt button to open a project in a new window, but that only works for historical projects that have already been opened, not for new projects.
![image](https://user-images.githubusercontent.com/28357731/121625610-61418d80-caa6-11eb-96c1-c972e524fe33.png)

**Comment by eamodio** [comment]
The ideal solution is blocked by https://github.com/microsoft/vscode/issues/88716

**Comment by JustinGrote** [comment]
@eamodio well is there a "non-ideal" solution, like opening a URL handler like git-vscode-remote://path/to/repo or something?

**Comment by eamodio** [comment]
You can use `vscode://github.remotehub/open?url=<github-url-here>` to do that today.

**Comment by JustinGrote** [comment]
@eamodio didn't work, pasted this into the browser, do I need to encode the parameters?
vscode://github.remotehub/open?url=https://github.com/microsoft/vscode-extension-samples

**Comment by eamodio** [comment]
Yes, sorry the url, needs to be url encoded: e.g. `vscode://github.remotehub/open?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fvscode`

**Comment by JustinGrote** [comment]
@eamodio it worked, thank you. also `vscode-insiders://` for the insiders version.

**Comment by eamodio** [comment]
yeah, the scheme is the edition of vscode (`vscode`, `vscode-insiders`, `vscode-exploration`), and you can also specify the insiders edition of Remote Repositories as well by changing the authority to `github.remotehub-insiders`

**Comment by joyceerhl** [comment]
This is fixed in main and will be resolved when we publish the next GitHub Repositories (Insiders) build.
