### ISSUE TITLE
Run application in terminal

### ISSUE THREAD

**Issue by Darkace01** [microsoft/vscode-remote-repositories-github#20]
I would love if there is some sort of virtual terminal or a way you can run the applications in the terminal with different cli's

**Comment by AmaanKulshreshtha** [comment]
Is there a way to run `npm` scripts, if the terminal is not there?

**Comment by JustinGrote** [comment]
@Darkace01 since it's a virtual filesystem, you almost certainly cant do anything like NPM or whatnot because those expect "real" files. That's what the "Continue on" button is for after you've "peeked" the repository, to continue in a local folder or into a container.

**Comment by Darkace01** [comment]
Oh thank you @JustinGrote
