### ISSUE TITLE
When deleting the last file in a folder that was also created, don't delete the folder

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode-remote-repositories-github#202]
Steps to reproduce:

* open https://insiders.vscode.dev/github/microsoft/vscode
* create a new untracked folder `foo`
* create a new untracked file in that folder `bar.txt`
* delete the file you just created `bar.txt`

Expected

The folder I just created (`foo`) shouldn't also be deleted

Actual 

The folder I just created (`foo`) is deleted.

**Comment by joyceerhl** [comment]
This is by design at the moment, I could see how it's not desirable though.

**Comment by joyceerhl** [comment]
No plans to change this behavior for now.
