### ISSUE TITLE
Unable to open remote repository

### ISSUE THREAD

**Issue by danthl** [microsoft/vscode-remote-repositories-github#203]
Issue Type: <b>Bug</b>

From the Open Files or Open Remote Repositories section, I click "Open Remote Repository", and it shows a list of my Github repos (this is all expected behavior).

However, when I click on the desired repo name (or any repo name) nothing happens. No errors, nothing happens.

Extension version: 0.12.0
VS Code version: Code 1.68.1 (30d9c6cd9483b2cc586687151bcbcd635f373630, 2022-06-15T02:58:26.441Z)
OS version: Linux x64 5.10.110-15808-ge5740beba59b
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|6.45GB (6.41GB free)|
|Process Argv|--unity-launch --crash-reporter-id d48842f3-443e-4fc3-b811-a2749ca7e978|
|Screen Reader|no|
|VM|100%|
|DESKTOP_SESSION|undefined|
|XDG_CURRENT_DESKTOP|X-Generic|
|XDG_SESSION_DESKTOP|undefined|
|XDG_SESSION_TYPE|undefined|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vsclangdc:30486549

```

</details>

**Comment by danthl** [comment]
I apparently needed to enable some other github extensions. nevermind.

**Comment by aeroquil** [comment]
do you remember what extensions they were? im having the same issue

**Comment by joyceerhl** [comment]
@aeroquil please ensure that you have enabled https://marketplace.visualstudio.com/items?itemName=github.remotehub and please file an issue if you continue to experience problems opening repositories. Thank you!
