### ISSUE TITLE
Default branch does not show up in Create New Branch From... picker

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-remote-repositories-github#206]
Reported by @karthiknadig. This is a discrepancy between GitHub Repositories and desktop git, we should align the behaviors.

**Comment by joyceerhl** [comment]
Repro steps:
1. Go to insiders.vscode.dev/github/microsoft/vscode (you should be on the main branch)
2. Use the Remote Repositories: Create New Branch from... command 
3. Verify that the main branch shows up as an option for the source branch

**Comment by rchiodo** [comment]
/verified

![image](https://user-images.githubusercontent.com/19672699/176743162-a5c31c20-f553-428e-bc0a-a93c0f44ee02.png)
