### ISSUE TITLE
Add a logo for Remote Repositories extension

### ISSUE THREAD

**Issue by segevfiner** [microsoft/vscode-remote-repositories-github#209]
Really? An official Microsoft extension with no logo in the marketplace? 😝. Sure you don't want to add one? 😉

**Comment by joyceerhl** [comment]
@daviddossett would you have the cycles to look into creating a logo for the Remote Repositories extension? This would be https://marketplace.visualstudio.com/items?itemName=ms-vscode.remote-repositories which both GitHub Repositories and Azure Repos integrate with. Let me know if I should file an issue elsewhere!

**Comment by daviddossett** [comment]
Yep should be able to tackle this.

**Comment by joyceerhl** [comment]
@daviddossett that looks great, thank you so much!
