### ISSUE TITLE
Logging in with a different GitHub account

### ISSUE THREAD

**Issue by afreed1377** [microsoft/vscode-remote-repositories-github#21]
I have multiple GitHub accounts. How can I sign out with one and sign in with another?

**Comment by alekkowalczyk** [comment]
I logged in but see only my repositories, not repositories from other accounts to which I have access - and cannot log out as well.

**Comment by eamodio** [comment]
Remote Repositories uses the built-in VS Code authentication providers/mechanisms. You can manage your logged in accounts in the Accounts icon in the activity bar. You could be able to sign in/out through there.

**Comment by afreed1377** [comment]
The status bar onthe bottom shows me as logged into BitBucket, but the Remote Repositories extension has me logged in with my personal GitHub account.

**Comment by eamodio** [comment]
@afreed1377 Check the Accounts icon on the activity bar -- that will have the VS Code accounts you are logged into -- which is what Remote Repositories uses.
