### ISSUE TITLE
Allow user to choose what vscode.dev quality to open a repo with

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-remote-repositories-github#211]
From @lszomoru -- currently Open on the Web in Remote Repositories opens a repo in insiders.vscode.dev if the command is invoked from Insiders and vice versa if invoked from Stable. We should instead allow the user to choose the quality.

**Comment by sandy081** [comment]
Found following issue while verifying 

https://github.com/microsoft/vscode-remote-repositories-github/issues/218
