### ISSUE TITLE
not opening repos

### ISSUE THREAD

**Issue by Saigenix** [microsoft/vscode-remote-repositories-github#214]
Issue Type: <b>Bug</b>

extention stops after loding nothing is showing after that

Extension version: 0.14.0
VS Code version: Code 1.69.1 (b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a, 2022-07-12T08:21:24.514Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

**Comment by joyceerhl** [comment]
@Saigenix do you have the GitHub Repositories extension installed and enabled? http://marketplace.visualstudio.com/items?itemName=github.remotehub

**Comment by Saigenix** [comment]
> @Saigenix do you have the GitHub Repositories extension installed and enabled? http://marketplace.visualstudio.com/items?itemName=github.remotehub

yes !

**Comment by Saigenix** [comment]
![Screenshot 2022-07-13 023947](https://user-images.githubusercontent.com/72882933/178595992-34abe29a-1439-4cbb-bd8b-5d97ee032717.png)
look

**Comment by joyceerhl** [comment]
That is a different extension--you will also need this:
![image](https://user-images.githubusercontent.com/30305945/178596464-405b0976-fd9f-446c-970b-6204cb65d130.png)

**Comment by Saigenix** [comment]
Thanks a lot! it is working now
