### ISSUE TITLE
Which vscode extension should I install?

### ISSUE THREAD

**Issue by snowman** [microsoft/vscode-remote-repositories-github#216]
There are two versions of it:

1. `GitHub.remotehub`
2. `ms-vscode.remote-repositories`

**Comment by joyceerhl** [comment]
`ms-vscode.remote-repositories` is an extension dependency of `GitHub.remotehub`. While you will need both, you should install `GitHub.remotehub`, which will also pull in `ms-vscode.remote-repositories`.
