### ISSUE TITLE
Menu: Go to Repository is ambiguous 

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-remote-repositories-github#217]
<img width="341" alt="image" src="https://user-images.githubusercontent.com/876920/180277358-58638aff-3c92-4954-aa51-9d49cce2720c.png">

I was reviewing PR on .dev and attempted to go back to the pull request page. The menu action says "Go to Repository" and I was thinking it would

* either go back to the home page of the repository, which reflects the name
* or go back to the pull request, which is what I want

However it opened a file blob url (based on the active diff editor in the workbench), this is probably the last thing I want to see as I was already reading the file content on .dev.

**Comment by joyceerhl** [comment]
This command used to go back to the home page of the repository but we changed its behavior a couple months ago.

That said it sounds like you want the GHPRI Open Pull Request on GitHub command:
![image](https://user-images.githubusercontent.com/30305945/180315339-bbed1280-721b-4675-be53-1efd07248177.png)
