### ISSUE TITLE
Cannot choose quality of vscode.dev after chose to open 

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode-remote-repositories-github#218]
- Open a remote repo
- Open on vscode.dev
- Choose insiders
- Again try open on vscode.dev
🐛 Quality is not shown. Quality picker is also not shown for a new remote repo. 

Why not have two commands `Open on insiders vscode.dev` and `Open on stable vscode.dev` instead?

**Comment by joyceerhl** [comment]
Looks like we just changed the share as links in the builtin GitHub extension to preserve the quality of VS Code (i.e. if I'm in insiders, open insiders.vscode.dev). To be consistent with that, we should probably do the same in RemoteHub (this does mean reverting the change for #211).
