### ISSUE TITLE
Install prompt loop on vscode.dev

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-remote-repositories-github#219]
1. Enter the URL of a repo not in the quickpick on vscode.dev -- for some reason, js-debug wasn't there

<img width="844" alt="image" src="https://user-images.githubusercontent.com/2230985/181602779-24a40479-e326-46c5-8e46-bbd912c77d4e.png">

2. See this prompt, even though the extension appears to already be installed

<img width="542" alt="image" src="https://user-images.githubusercontent.com/2230985/181602841-9adb14bd-40cc-4ed4-a96c-686c58eb4a17.png">

3. Hit "install" reload, and repeat

I think it wasn't expecting just the `<owner>/<repo>` form as input, as pasting a whole GH URL works. I think this should work or not fail in a bad way like this.

**Comment by connor4312** [comment]
I also hit this on desktop when picking a repository though the "Open Repository from GitHub" action

**Comment by joyceerhl** [comment]
Hmm on desktop do you have GitHub Repositories installed and enabled? @connor4312

**Comment by connor4312** [comment]
Okay, so, I _do_. And if I run the command on an empty window I get that behavior. But if I run that command when I already have a remote repository open, I don't get the issue. So I'm guessing it's likely an extension activation problem.

**Comment by joyceerhl** [comment]
This should not happen anymore now that we've broken the picker's dependency on the git-base extension.

**Comment by connor4312** [comment]
I think there still might be something up here:

1. Open an empty window
2. "Open remote repository"
3. Enter `owner/repo` for something you don't have write access and thus isn't in the picker
4. Selecting the "Enter a Remote URL" does nothing

<img width="631" alt="image" src="https://user-images.githubusercontent.com/2230985/234723066-007746e9-6744-48af-b149-0bf731400a0b.png">

I would expect that action to work, or for there to be some action like "Open nodejs/node from GitHub"

However the "js-debug wasn't there" problem does appear to be fixed 🙂

**Comment by joyceerhl** [comment]
> something you don't have write access and thus isn't in the picker

The recently opened picker shows workspaces that you've viewed before, regardless of whether you have write access to it, so the only criteria for whether it appears in the first-level picker is that you've opened it before.

> for there to be some action like "Open nodejs/node from GitHub"

Not sure why this hasn't occurred to me before :) we could just show the Open Repository from GitHub / Azure Repos actions again, and feed the current input query to those actions. Tracking that in https://github.com/microsoft/vscode-remote-repositories-github/issues/264. Thanks for testing!
