### ISSUE TITLE
How to remove Remote Repo from Remote Explorer View?

### ISSUE THREAD

**Issue by ShadowCreator250** [microsoft/vscode-remote-repositories-github#22]
I can't find a command or GUI element that allows me to remove a remote repo where I finished working on.  
I also couldn't find anything regarding this in the docs.  

Can someone help me or give me a tip?

**Comment by eamodio** [comment]
This will be in the June 2021 release.

**Comment by eamodio** [comment]
This has been resolved in the latest Remote Repositories insiders edition.

If you want to verify this fix, you can install the Remote Repositories insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=GitHub.remotehub-insiders).

Please be sure to disable or uninstall the stable version of Remote Repositories first. Also note, that no data is shared between the insiders and stable editions.
