### ISSUE TITLE
Way to get branch name

### ISSUE THREAD

**Issue by chikaishiro** [microsoft/vscode-remote-repositories-github#222]
Hi, I'm building a Vscode extension with your extension to connect to remote github repositories. Since I need to get current  branch information (name for example) from an repository opended with the extension, I'm wondering if there is a way or existing API to get branch information with this extension? Thanks a lot!

My current way is using the extension "vscode.git" to get branch name.
![image](https://user-images.githubusercontent.com/26539304/182349962-944a9926-959b-4df6-b480-10a619c4b387.png)
But the console output is "undefined".

**Comment by joyceerhl** [comment]
This is possible today but through a different API shape than the API exposed by `vscode.git`:

```ts
	async function getBranchNameForRepository(folderUri: vscode.Uri): Promise<string | undefined> {
		const extension = vscode.extensions.getExtension('ms-vscode.remote-repositories');
		if (extension !== undefined) {
			const api = await extension.activate();
			const repositoryMetadata = await this.getMetadata(folderUri);
			return (await repositoryMetadata?.getRevision())?.name;
		}
		return undefined;
	}
	
```
