### ISSUE TITLE
Searching after canceling the index download only searches open files

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-remote-repositories-github#224]
Testing microsoft/vscode#143575

Maybe I'm misunderstanding what the github api would return but I think there's an issue here.

Repro steps:
1. On desktop use github remote to connect to https://github.com/plotly/plotly.js/
2. Open search panel
3. Type in `module.exports`
4. Hit return
5. Cancel the download of the full index

Actual result:
Search results will be empty

Expected result:
I think it should find all the 'module.exports' in all of the js files. If you open a single js file, it will find 'module.exports' in that file.

**Comment by joyceerhl** [comment]
Closing as there's nothing we can do about this now. We can revisit whenever the new GitHub code search API becomes available.
