### ISSUE TITLE
github.dev Create Pull Request action uses the entire commit message as a title

### ISSUE THREAD

**Issue by gibson042** [microsoft/vscode-remote-repositories-github#226]
Version: 1.70.0
Commit: da76f93349a72022ca4670c1b84860304616aaa2
User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.72 Safari/537.36
Embedder: github.dev

----

(observed at https://github.com/jmespath-community/jmespath.site/pull/23 )

In the github.dev editor source control section, it is possible to commit changes and automatically create a pull request. But when the commit message has multiple lines (i.e., a single-line subject and nonempty body, separated by a blank line), the resulting pull request has an empty body and a title formed by concatenating the commit's subject and body with medial whitespace removed. For example, a commit message like
```
git commit subject

git commit body
```
results in a pull request title like `git commit subjectgit commit body`.

Instead, the pull request's title should match the commit's subject and the pull request's body should match the commit's body.

**Comment by gibson042** [comment]
I don't see the repository in which a fix was implemented, but presumably it was adjusting the result of `<var1> = <var2>.inputBox.value` (which appears before `<var3>.inputBox.showValidationMessage(…)` guarded by `if (!<var1)`), ultimately used as the `value` option for `<var4>.window.showInputBox`.

**Comment by joyceerhl** [comment]
With the fix, PRs created with a single commit and a multiline commit message will now have the first line of the commit message used to populate the PR title and the rest of the commit message used to populate the description. This fix will ship with the August stable release at the end of the month, or you can use https://insiders.vscode.dev/github/<owner>/<repo> where the fix is already live

**Comment by roblourens** [comment]
Sorry how do I do this "Commit and pull request" instead of "Commit and push" on vscode.dev?

**Comment by joyceerhl** [comment]
You need to be on a repo that you don't have write access to -- in that scenario the commit input box will say create pull request instead of commit and push.

**Comment by TylerLeonhardt** [comment]
works 😅 
https://github.com/facebook/react/pull/25146
