### ISSUE TITLE
Unable to open file name [...something].js

### ISSUE THREAD

**Issue by empz** [microsoft/vscode-remote-repositories-github#23]
NextJS has a special route filename that involves the following file name pattern `[...something].js`.

This extension is having issues opening the file. Even though the explorer shows the file in the file tree, opening it results in the following error:

```
Unable to open '[...nextauth].js': Unable to read file 'vscode-vfs://github/nextauthjs/next-auth-example/pages/api/auth/[...nextauth].js' (Error: Unable to resolve non-existing file 'vscode-vfs://github/nextauthjs/next-auth-example/pages/api/auth/[...nextauth].js').
```

**Comment by eamodio** [comment]
I dug into this one, and it looks like a bug in the GitHub GraphQL api -- I've reached out to see how to best resolve this.

**Comment by eamodio** [comment]
This is blocked until the GitHub API issue is fixed.

**Comment by joyceerhl** [comment]
This should be resolved now. Please let us know if otherwise.
