### ISSUE TITLE
Reopen on the Desktop does not preserve branch context

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-remote-repositories-github#232]
1. Have a branch open like https://insiders.vscode.dev/github/microsoft/vscode/tree/dev/joyceerhl/beautiful-crayfish
2. Choose Continue Working On > Reopen on the Desktop
3. :bug: the main branch is opened

**Comment by aiday-mar** [comment]
Hi Joyce, I am not sure if I am using the feature correctly so perhaps there is no problem. I link here an issue that I opened: https://github.com/microsoft/vscode-remote-repositories-github/issues/236
