### ISSUE TITLE
Consider renaming 'Reopen on the Desktop' option for Continue Working On

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-remote-repositories-github#234]
@jrieken had feedback that it wasn't clear what this Continue Working On option does, it is somewhat ambiguous. Wondering if something like 'Open in Desktop App' would work.

**Comment by Sidarta85** [comment]
> @jriekenteve comentários de que não estava claro o que essa opção Continuar trabalhando em faz, é um pouco ambíguo. Querendo saber se algo como 'Abrir no aplicativo para desktop' funcionaria.

**Comment by Kode5653** [comment]
Please! Place windows Drive in first brackket rather then before hypre link of the uri-e as so

**Comment by joyceerhl** [comment]
Duplicate of https://github.com/microsoft/vscode/issues/167607, resolved in the November 2022 update.
