### ISSUE TITLE
Open Remote Repository lists unsupported GitLab option

### ISSUE THREAD

**Issue by x-sheep** [microsoft/vscode-remote-repositories-github#237]
I have the official [GitLab Workflow](https://marketplace.visualstudio.com/items?itemName=GitLab.gitlab-workflow) extension installed, which connects into the "Clone Repository" function of VS Code. It seems that Remote Repositories uses the same list when selecting "Open Remote Repository".

![Screenshot_2022-08-23_at_13 11 51](https://user-images.githubusercontent.com/7021451/187154619-9c3d99af-3f93-4696-ba03-bc3a66b3b9ae.png)

Clicking this option will guide me through the menus for cloning a GitLab repository. Completing this will ask me for the GitHub Repositories extension, which I have installed already. Clicking "Install" only restarts VS Code without actually opening the repository.

![Screenshot_2022-08-23_at_13 12 14](https://user-images.githubusercontent.com/7021451/187154855-012d8c4b-c9c0-41fe-ad6a-bfac1257866e.png)

The GitLab extension does support opening a repository without cloning it, but the Remote Repositories extension does not seem to have a way to allow other extensions to integrate with it.

## Versions

Visual Studio Code version 1.70.2
Remote Repositories 0.18.0
GitHub Repositories 0.40.0
GitLab Workflow 3.48.1

## Other references:
[The same issue on the GitLab Workflow issue board](https://gitlab.com/gitlab-org/gitlab-vscode-extension/-/issues/617)

**Comment by joyceerhl** [comment]
Related to https://github.com/microsoft/vscode/issues/136890

**Comment by joyceerhl** [comment]
This is obsolete now that the Open Remote Repository picker doesn't integrate with the git base extension's remote sources API.

**Comment by x-sheep** [comment]
The latest pre-release fixed the underlying bug, so this is fine by me 👍
