### ISSUE TITLE
Empty folders are not preserved on branch switch.

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode-remote-repositories-github#251]
1. Open github.dev
2. Create an empty folder i.e. 'testfolder'
3. Try to switch to a new branch, you'll be told your uncommitted changes will come with.
4. 🐛 The empty folder is not carried over.

If the folder has an uncommitted file in it as well then it is carried over.

**Comment by joyceerhl** [comment]
The current mechanism for preserving uncommitted changes when switching branches is the unidiff format. Git does not track folders, only files, so we would need some additional, nonstandard, mechanism for also preserving folders on a branch switch. Closing as we're unlikely to address this in the near future.
