### ISSUE TITLE
Creating a new branch should leverage the branch generation setting from git

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode-remote-repositories-github#253]
cc @lszomoru

**Comment by joyceerhl** [comment]
Related: https://github.com/microsoft/vscode-remote-repositories-github/issues/252

**Comment by joyceerhl** [comment]
Verification:
1. Configure `"git.branchPrefix"` in your settings
2. Go to https://insiders.vscode.dev/github/microsoft/vscode
3. Make a change
4. Commit the change while on the main branch
5. You should instead get a modal dialog that says you're trying to commit to a protected branch 
6. Verify that your configured branch prefix is picked up in the flow to create a branch
