### ISSUE TITLE
Create branch if it doesn't already exist

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-remote-repositories-github#257]
- If you try to visit a branch that doesn't exist e.g. https://vscode.dev/github/microsoft/vscode-remote-repositories-github/tree/dev/non-existent-branch, you get dropped into an empty workspace, which is a broken experience
- If you want to create a branch that doesn't already exist, a common workflow for this today is github.com -> hit `.` to open in github.dev -> Create New Branch (as reported by @digitarald)

We could improve on both of these issues by displaying a dialog when you access a nonexistent branch that says
> "The branch `dev/non-existent-branch` does not exist. Would you like to create and switch to it?"

**Comment by digitarald** [comment]
It would be interesting to see how instant this can feel, reducing the number of prompts. `https://vscode.dev/github/microsoft/vscode-remote-repositories-github/new` could create a branch using the random name generator and drop you right into it. `https://vscode.dev/github/microsoft/vscode-remote-repositories-github/new/1234` could auto-create a branch using the same rules as GHPRIs `Start working on issue`.
