### ISSUE TITLE
Open Remote Repository picker improvements

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-remote-repositories-github#264]
- Should show options to search repos/PRs from registered providers if the query in first level of picker isn't a valid URL
- Should always be able to paste a URL into Open Remote Repo picker even if in second level of picker
- Investigate users apparently having trouble searching for repositories

**Comment by eleanorjboyd** [comment]
I got the other two steps verified, but what does this mean "Should show options to search repos/PRs from registered providers if the query in first level of picker isn't a valid URL". How do I get an invalid first level picker?

**Comment by joyceerhl** [comment]
To rephrase: type something into the first level of the picker that isn't a valid URL, and make sure that the options to search repos/PRs aren't filtered out
