### ISSUE TITLE
Improve experience when installing Remote Repositories without GitHub Repositories or Azure Repos

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-remote-repositories-github#265]
- Declare Remote Repositories an extension pack
- Display a modal on install

**Comment by joyceerhl** [comment]
Verification: 
1. Uninstall GitHub Repositories, Azure Repos, and Remote Repositories if you already have them
1. Install Remote Repositories 
2. GitHub Repositories and Azure Repos should also be installed

**Comment by bhavyaus** [comment]
Verified that GitHub Repositories and Azure Repos are also installed when not present.
