### ISSUE TITLE
Adopt proposed telemetry API

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-remote-repositories-github#266]

**Comment by joyceerhl** [comment]
Verification: have Remote Repos installed and verify that Remote Repos telemetry logging appears in the output channel.

**Comment by alexr00** [comment]
I had to set the log level to `trace` before the telemetry output channel showed. @lramos15 is it supposed to work this way? The message at the start of the output channel makes me think that the channel is always supposed to be there, just mostly empty until you set `trace`:

```
2022-11-29 11:29:07.529 [info] Below are logs for extension telemetry events sent to the telemetry output channel API once the log level is set to trace.
2022-11-29 11:29:07.529 [info] ===========================================================
```

**Comment by lramos15** [comment]
> I had to set the log level to `trace` before the telemetry output channel showed. @lramos15 is it supposed to work this way? The message at the start of the output channel makes me think that the channel is always supposed to be there, just mostly empty until you set `trace`:
> 
> ```
> 2022-11-29 11:29:07.529 [info] Below are logs for extension telemetry events sent to the telemetry output channel API once the log level is set to trace.
> 2022-11-29 11:29:07.529 [info] ===========================================================
> ```

It's supposed to work this way, the same way the core telemetry channel works
