### ISSUE TITLE
[issue] cache the file downloading from github

### ISSUE THREAD

**Issue by jianboy** [microsoft/vscode-remote-repositories-github#27]
reading the code with VSCode. It is not watching the novel from first to the end.

We often see a function that needs to jump to another file to see it definition. but when we return current file, it will download from github again.

for example, add a config:
```
vscode-remote-repositories-github.cachesize: 100M
```

**Comment by eamodio** [comment]
This has been resolved in the latest Remote Repositories insiders edition.

If you want to verify this fix, you can install the Remote Repositories insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=GitHub.remotehub-insiders).

Please be sure to disable or uninstall the stable version of Remote Repositories first. Also note, that no data is shared between the insiders and stable editions.
