### ISSUE TITLE
Close diff editor on commit

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-remote-repositories-github#270]
From @roblourens 

> Would be great if the diff editor would close automatically after committing, as it does with git when I set `git.closeDiffOnOperation`.
>
> I usually click through diffs to double check before committing, then have a stale diff editor open that I have to close manually.

**Comment by roblourens** [comment]
Cool, thanks!

**Comment by joyceerhl** [comment]
Verification:
1. In insiders.vscode.dev/github/microsoft/vscode enable `git.closeDiffOnOperation` (if you had this on desktop and enabled settings sync in vscode.dev the setting should already be there)
2. Make some changes
3. Open diffs for those changes
4. Stage or commit those changes
5. If you staged or unstaged a specific file, the diff editor for that file should close. If you committed multiple changes, all diff editors for the changed files should close
6. File issues for any behavior that doesn't work as expected

**Comment by alexr00** [comment]
Verified when only one file is changed, but not when multiple changed: https://github.com/microsoft/vscode-remote-repositories-github/issues/279
