### ISSUE TITLE
Command '>Remote Repositories: open Remote Repository...' fails instantly

### ISSUE THREAD

**Issue by jvillemure** [microsoft/vscode-remote-repositories-github#275]
Vscode version:
> Version: 1.73.1 (user setup)
Commit: 6261075646f055b99068d3688932416f2346dd3b
Date: 2022-11-09T04:27:29.066Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19045
Sandboxed: No

Ran with all extensions disabled except:
> Name: Remote Repositories
Id: ms-vscode.remote-repositories
Description: Remotely browse and edit git repositories
Version: 0.25.2022111801
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-vscode.remote-repositories

> Name: Azure Repos
Id: ms-vscode.azure-repos
Description: Remotely browse and edit any Azure Repos
Version: 0.23.2022111701
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-vscode.azure-repos

> Name: GitHub Repositories
Id: GitHub.remotehub
Description: Remotely browse and edit any GitHub repository
Version: 0.47.2022111701
Publisher: GitHub
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=GitHub.remotehub

When using the *prerelease* versions of the extensions `Remote Repositories`, `Azure Repos` and `GitHub Repositories`, invoking the command `>Remote Repositories: open Remote Repository...` from the command palette results in an instant dialog box with the message:

> Command 'Remote Repositories: Open Remote Repository...' resulted in an error (command 'remoteHub.openRepository' not found)

None of those extension get activated by any kind of `>Remote Repositories: ...` commands in the command palette.

Also the widgets from the Remote Repositories View have broken behaviour:
![Screenshot 2022-11-19 133225](https://user-images.githubusercontent.com/35437328/202866345-75ca6de5-fd62-4791-ab07-a51850262caa.png)

Pressing the Refresh button brings an error notification:
> Error running command remoteHub.views.workspaceRepositories.refresh: command 'remoteHub.views.workspaceRepositories.refresh' not found. This is likely caused by the extension that contributes remoteHub.views.workspaceRepositories.refresh.

And pressing the Add button also brings an error notification:
> Error running command remoteHub.openRepository: command 'remoteHub.openRepository' not found. This is likely caused by the extension that contributes remoteHub.openRepository.

None of these bugs occurs when using the *release* versions of these extensions:
> Name: Remote Repositories
Id: ms-vscode.remote-repositories
Description: Remotely browse and edit git repositories
Version: 0.24.0
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-vscode.remote-repositories

> Name: Azure Repos
Id: ms-vscode.azure-repos
Description: Remotely browse and edit any Azure Repos
Version: 0.22.0
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-vscode.azure-repos

> Name: GitHub Repositories
Id: GitHub.remotehub
Description: Remotely browse and edit any GitHub repository
Version: 0.46.0
Publisher: GitHub
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=GitHub.remotehub

**Comment by joyceerhl** [comment]
The latest pre-release requires VS Code 1.74-insider--I'll push a fix for this which will prevent future pre-releases from being treated as compatible with 1.73 stable. In the meantime please consider using VS Code Insiders with the pre-release Remote Repos extensions.
