### ISSUE TITLE
Rename groups in command palette from `Remote Repositories` to `Git`

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-remote-repositories-github#277]
@jrieken had interesting feedback that he does not use vscode.dev with Remote Repos as much as he should because he searches for `Pull` and sees `Remote Repositories: Pull` instead of `Git: Pull`, and it feels unfamiliar compared to desktop. To make things more familiar to users I wonder if we should change the command group name to also be `Git`? The hypothesis is that making such a change would encourage more users to use git commands via the command palette.

cc @lszomoru for feedback

**Comment by lszomoru** [comment]
One potential issue with using "Git" would be that users might assume that all the git functionality that is available on desktop is now available in the web, while at the moment we only support GiHub and Azure Repos on the web. Ideally we would want to use either `GitHub: ...` or `Azure Repos: ...` for the commands through I am not sure that is feasible since the commands are defined in the Remote Repositories extension.

**Comment by jrieken** [comment]
> One potential issue with using "Git" would be that users might assume that all the git functionality that is available on desktop is now available in the web

My brain is weird and I simply press F1, type "pull" and when I don't see "Git: Pull" atop I am confusing and give up. I share your concern about giving a false impression but AFAIK can tell git-pull does the same on web and desktop so could make this a case by case thing. Alternatively we could call it "Git: Pull from Remote Repository". I guess my takeaway is that the category-label, like "Git:", shouldn't name extensions but features

**Comment by joyceerhl** [comment]
We haven't heard similar feedback in a year so I'm not persuaded to change this for everyone. With the semantic similarity work though, maybe we can get Remote Repos to match Git in command palette search results? @TylerLeonhardt do you think that would make sense?

**Comment by TylerLeonhardt** [comment]
It might find it... and if it doesn't, we'd need a way for an extension to contribute a description that can include some common wording to be searched. That's tracked in an issue already https://github.com/microsoft/vscode/issues/195573

unless it's a Core command, then we can already add a description
