### ISSUE TITLE
Diffs not closed on operation

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-remote-repositories-github#279]
Testing https://github.com/microsoft/vscode-remote-repositories-github/issues/270

This worked find for just one file, but when I staged/unstaged multiple files, no diffs were closed:

1. https://insiders.vscode.dev/github/microsoft/vscode/tree/alexr00/sudden-mockingbird
2. Make a change in 3 different files
3. Open a diff from the SCM view
4. Stage all files
5. 🐛 diff isn't closed

**Comment by meganrogge** [comment]
This did not work for me (the diff remained open)

**Comment by joyceerhl** [comment]
Kicked off a new pre-release of Remote Repositories, please try again in ~10 minutes
