### ISSUE TITLE
"Reopen on the web" should work without Microsoft account

### ISSUE THREAD

**Issue by LinqLover** [microsoft/vscode-remote-repositories-github#28]
When I run the "Reopen on the web" command, I am not directed to github.com but instead to some dubious `https://vscode.dev/github.com` URL. Even worse, this page does not redirect me to GitHub unless I log in with my Microsoft account and it even requires me to do a phone code verification when trying to log in!

Usually, I'm definitively not a MS hater, these days you build so much awesome software, but in this example, this is just unnecessary and patronizing and the opposite of data minimalism. Can't you please just redirect me to the respective GitHub URL? Or alternatively, at least make the login on vscode.dev optional!

**Comment by eamodio** [comment]
Doh -- this is fixed in the next release. It should have been going to `github.com` 🤦‍♂️

**Comment by LinqLover** [comment]
Thank you! 😅
