### ISSUE TITLE
SCM shows stale diff contents after a pull

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-remote-repositories-github#280]
Reported by @sbatten 

1. Open the same repo in insiders.vscode.dev and github.dev
2. Make a change to a file in insiders.vscode.dev
3. Make a non-conflicting change to the same file in github.dev
4. Commit from github.dev
5. Pull from insiders.vscode.dev (no merge conflicts should be flagged at this stage)
6. Open the diff from the SCM view 
7. :bug: the diff reflects the combination of changes from the github.dev commit and the unpushed local commits. Clicking the refresh button in the SCM view is sufficient to fix the stale diff contents

Likely the LHS of the diff command still points to the SHA before pulling, and we need to recompute the SCM resource states and commands when the repository is synced to ensure that the diff editor reflects the correct contents.

**Comment by meganrogge** [comment]
I followed the steps above, did `Commit & Push`, pulled in VS Code Insider's Desktop on the same branch/same repo, and do not see the changes that I pushed in insiders.vscode.dev. But when I commit in Desktop and try to push, I'm told there are changes to pull 🤔 . Maybe a timing issue?

![Screenshot 2023-01-26 at 12 24 56 PM](https://user-images.githubusercontent.com/29464607/214918702-1d363e16-e4fb-43aa-aba4-826f77b6dd4f.png)

**Comment by meganrogge** [comment]
I tried the sequence again and it worked the second time around

**Comment by meganrogge** [comment]
I never saw a stale diff, so am considering this verified
