### ISSUE TITLE
Adopt quick pick item guidance in Remote Repositories

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-remote-repositories-github#281]
We now have team wide quick pick item guidance https://github.com/microsoft/vscode/issues/158895

We should adopt this guidance in Remote Repositories' pickers.

_Originally reported by @jrieken_

* be on vscode.dev
* pick a branch form the status bar picker
* picker has a title and that's something we usually don't do, e.g desktop/file doesn't

<img width="458" alt="Screen Shot 2021-06-03 at 09 58 38" src="https://user-images.githubusercontent.com/1794099/120613077-2a3ffc00-c456-11eb-8911-9576e2c0aa15.png">

<img width="704" alt="Screen Shot 2021-06-03 at 10 27 07" src="https://user-images.githubusercontent.com/1794099/120613179-43e14380-c456-11eb-8a37-47b05c9901d7.png">

**Comment by eleanorjboyd** [comment]
is there anything extra I need in order to get the new version of vscode.dev? Currently, it seems my quick picker still has a title
<img width="693" alt="Screenshot 2023-01-25 at 8 16 06 AM" src="https://user-images.githubusercontent.com/26030610/214616812-d97bd5a6-2c66-4ecb-86f3-157b81dc4777.png">

**Comment by joyceerhl** [comment]
Are you using insiders.vscode.dev or vscode.dev?

**Comment by eleanorjboyd** [comment]
hm I was actually on github.dev- I should be using insider.vscode.dev?

**Comment by joyceerhl** [comment]
Yes, please use insiders.vscode.dev as that ships both latest VS Code Insiders and latest RemoteHub. github.dev only ships stable RemoteHub regardless of VS Code quality, so should not be used for VS Code verification
