### ISSUE TITLE
Provide PR view for Azure Repos

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-remote-repositories-github#282]
_Originally reported by @alexdima_

> When opening a PR, I would expect to see a view which shows me all changes in the PR such that I can open and look at the diffs.

From @lszomoru 

> PR support is currently very limited as it is being provided by code in the Remote Repositories and Azure Repos extensions. The view that you are looking is currently implemented in the GHPR extension, and in the future we will be looking at ways to add support for Azure Repos PRs in the GHPR extensions.

**Comment by hazem454** [comment]
> _Originally reported by @alexdima_
> 
> 
> 
> > When opening a PR, I would expect to see a view which shows me all changes in the PR such that I can open and look at the diffs.
> 
> 
> 
> From @lszomoru 
> 
> 
> 
> > PR support is currently very limited as it is being provided by code in the Remote Repositories and Azure Repos extensions. The view that you are looking is currently implemented in the GHPR extension, and in the future we will be looking at ways to add support for Azure Repos PRs in the GHPR extensions.
