### ISSUE TITLE
Visual Studio Code 1.58.2 compatible version 

### ISSUE THREAD

**Issue by ncblx** [microsoft/vscode-remote-repositories-github#286]
Hi All,
Could you please help to download extension compatible with VSC version 1.58.2? 

Thanks

**Comment by joyceerhl** [comment]
You can click on the gear icon in the bottom right for the extension that you're interested in and use the `Install Another Version` option to find an extension which is compatible with the current version of VS Code that you have installed. As v1.58.2 was released in June 2021 I would also recommend to update your install of VS Code.

![image](https://user-images.githubusercontent.com/30305945/213774246-45c43160-6725-4f2d-a1d9-f8a2207d8221.png)

**Comment by ncblx** [comment]
This function not available on my VSCode version. I could not update it based on internal corporate rules.
