### ISSUE TITLE
Continue Working on the Web times 2

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode-remote-repositories-github#289]
![image](https://user-images.githubusercontent.com/2644648/214657485-3887d29f-b228-449c-bf57-a7893ce5bea7.png)

I only have these extensions since this is a fresh Exploration build:
![image](https://user-images.githubusercontent.com/2644648/214657595-a7f99ef4-4f91-4a87-bc05-3125cfaa47aa.png)

Version: 1.75.0-exploration (Universal)
Commit: ac229ad6e485f87b5c172a909c5aafe333cad9ce
Date: 2023-01-24T12:42:54.206Z
Electron: 22.0.3
Chromium: 108.0.5359.179
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.2.0
Sandboxed: Yes

**Comment by joyceerhl** [comment]
That is super weird. This is a desktop git repo?

**Comment by TylerLeonhardt** [comment]
Yes that's right. VS Code repo

**Comment by joyceerhl** [comment]
This has been fixed in VS Code itself. Repro: open the remote indicator, install or uninstall an extension, then open the remote indicator again. There should only be one `Continue Working in vscode.dev` item.
