### ISSUE TITLE
option to delete the remote repository list in the remote explorer in vs code

### ISSUE THREAD

**Issue by hritikhrk** [microsoft/vscode-remote-repositories-github#29]
There should be an option to delete the remote repository from that list in the remote explorer in vs code.
<br>
![Screenshot from 2021-06-25 02-10-01](https://user-images.githubusercontent.com/57057779/123329532-8b8d5380-d55a-11eb-9fe7-0d3b161f92ff.png)
<br>
I don't want the second repo to be in this list. How can I do that?

**Comment by eamodio** [comment]
This will be fixed in the next release.

**Comment by jcatumba** [comment]
I can see the option on a recently added remote repository. But, for an older one that doesn't show any contextual menu when right-clicking its name.

**Comment by joyceerhl** [comment]
@jcatumba can you share a screenshot of the repositories view when you try to right click on an older entry?

**Comment by jcatumba** [comment]
@joyceerhl here is the screenshot. I see the menu for the top repository but for the second one nothing happens:
![imagen](https://github.com/microsoft/vscode-remote-repositories-github/assets/1387668/b6450f2f-cdf9-4db7-a44e-2504327ff1da)
Here is when I try on the first one:
![imagen](https://github.com/microsoft/vscode-remote-repositories-github/assets/1387668/624cd1a7-d81b-4761-be25-5022cc173c78)

**Comment by joyceerhl** [comment]
@jcatumba try expanding the second one and then right clicking on the specific branches you want to remove?

**Comment by jcatumba** [comment]
> @jcatumba try expanding the second one and then right clicking on the specific branches you want to remove?

Thanks! Is gone now.
