### ISSUE TITLE
Would a separator be nice for the branch picker?

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode-remote-repositories-github#290]
| GitHub Repos | Git |
|--------|--------|
| ![image](https://user-images.githubusercontent.com/2644648/214658207-44b18b7e-b6bf-4438-82a0-8a0cb77ffc39.png) | ![image](https://user-images.githubusercontent.com/2644648/214658359-0ede0f56-f971-4838-9ac8-033dc9c91aed.png) | 

For our branch pickers... I feel like a separator would be nice to separate the actions at the top and the branches. I'm thinking a single separator after the actions at the top that says `branches` or `existing branches`

Thoughts?

**Comment by lszomoru** [comment]
I was just thinking of adding a separator without any label.

**Comment by daviddossett** [comment]
Agreed that a separator would really help here. 

@lszomoru @TylerLeonhardt are there any a11y concerns by not including a label? Do we do that elsewhere? Obviously that's the behavior w/o the separator today, but I wonder if it would be a nice bonus to have the sections distinguished with a screen reader.

**Comment by joyceerhl** [comment]
We could have separator groups for branches, tags, and remote branches, since these QPIs are currently only distinguishable based on the codicon:
<img width="608" alt="image" src="https://user-images.githubusercontent.com/30305945/214661603-288394b9-3881-4e54-a601-0ded9f75c495.png">

**Comment by lszomoru** [comment]
Do we support separators with a label? Is there a place where we are using such a separator?

**Comment by joyceerhl** [comment]
Yeah, see for example the Open Remote Repo picker which has the `remote sources` and `recently opened` quick pick separators with labels 
<img width="722" alt="image" src="https://user-images.githubusercontent.com/30305945/214664904-aae37c6d-d492-42a1-8abf-c2e3e7205a4a.png">

**Comment by daviddossett** [comment]
> Do we support separators with a label? Is there a place where we are using such a separator?

Yeah it's somewhat confusing because separators are coupled with labels even though the label looks like it's rendered on a different element.

**Comment by TylerLeonhardt** [comment]
Oh yeah I forgot about tags... a separator without a label also seems fine to me since it's kinda obvious what's in the list.

Or the label could be `ref` since that's git-y

We could also add more separation as @joyceerhl suggests because when you filter, the separators will go away anyway as the results will be sorted... with that said, my list is full of branches and tags... so I'm not sure I'll ever do anything other than search.

**Comment by lszomoru** [comment]
I would just go with a separator to separate the actions from the "refs":

<img width="875" alt="image" src="https://user-images.githubusercontent.com/3372902/214670199-0b8d4600-b17d-4c80-b0d2-d512a1372dcf.png">

**Comment by joyceerhl** [comment]
Duplicate https://github.com/microsoft/vscode-remote-repositories-github/issues/315, this was implemented in April for Remote Repos to match the git extension.
