### ISSUE TITLE
Repo list does not include all available repos when trying to open a new repo after previously opening one.

### ISSUE THREAD

**Issue by bhavyaus** [microsoft/vscode-remote-repositories-github#293]
1. Launch  code-insiders and open a remote repo
2. Switch back to the remote explorer view and try to add another remote repo

Expected:
List should show all available repo's (incase of search text being entered, the search matches should show up at the top)

Actual:
Only some repos (looks like only private and starred repo's) show up. Searching for a specific repo does not yield any result.

<img width="499" alt="image" src="https://user-images.githubusercontent.com/25044782/214956939-380ad814-60fd-465c-859a-ce7c390eb21c.png">

**Comment by dbaeumer** [comment]
Using `microsoft/vscode` didn't list the VS Code main repository for me in the list. Only adding a blank at the end did. Reopening for investigation. @joyceerhl you can close the issue again if this is expected.

**Comment by joyceerhl** [comment]
@dbaeumer this seems to work as expected for me:

Desktop:
![image](https://user-images.githubusercontent.com/30305945/220744212-9967c183-066d-4e20-b3c4-5d1b58fccf1a.png)
Web:
![image](https://user-images.githubusercontent.com/30305945/220744243-6df535e6-0196-4af2-b4d8-f3eddc11a388.png)

Do you have a consistent repro?

**Comment by dbaeumer** [comment]
I tried it again today and now it is there :-). I am 100% sure I wasn't yesterday. I even scrolled through the whole list to ensure it is not a sorting issue.

Will close as verified.
