### ISSUE TITLE
gitProtocol setting (ssh) is ignored

### ISSUE THREAD

**Issue by aetonsi** [microsoft/vscode-remote-repositories-github#294]
Hello
I'd like to know if i'm doing something wrong or if there's some problem with the extension.
I have `"remoteHub.gitProtocol": "ssh"` in my loaded settings, yet, when i try to clone a repository locally with either of these commands:
![image](https://user-images.githubusercontent.com/18366087/215068575-cb2e19f8-cb12-4533-b964-6ae0b4bed015.png)
... the result is always the same, it tries to use https instead of ssh:
![image](https://user-images.githubusercontent.com/18366087/215069457-2bb65c80-c254-49fc-b4dc-7536e03c0d7e.png)

In my global git config I have all transports disabled **except** for ssh, so the clone fails:
```log
2023-01-27 11:50:52.803 [info] > git clone https://github.com/mmikeww/AHK-v2-script-converter c:\_\AHK-v2-script-converter --progress --branch master [78ms]
2023-01-27 11:50:52.803 [info] Cloning into 'c:\_\AHK-v2-script-converter'...
fatal: transport 'https' not allowed
2023-01-27 11:51:01.455 [info] > git clone https://github.com/mmikeww/AHK-v2-script-converter c:\_\AHK-v2-script-converter --progress --branch master [75ms]
2023-01-27 11:51:01.455 [info] Cloning into 'c:\_\AHK-v2-script-converter'...
fatal: transport 'https' not allowed
```

Am i missing something? Shouldn't it be using ssh?
Also, what's the difference between those 2 commands? They run the exact same git clone command

Thanks

**Comment by aetonsi** [comment]
@joyceerhl Thanks for the fix! 

Quick question: what's the difference between "Continue working in new local clone" and "Clone repository locally and open on desktop" ?
They seem to run the same command.

Thanks

**Comment by joyceerhl** [comment]
They are indeed the same command, just with a different name depending on UI context. The fix is in the latest pre-releases of Remote Repositories.

**Comment by joyceerhl** [comment]
Do you see both those commands in the command palette? If so, that is a bug--what version of the Remote Repositories extension do you have installed?

**Comment by aetonsi** [comment]
I can confirm this very issue has been solved in the pre release. Thanks!

But yes, i see both cloning commands, stable or pre-release version doesn't make a difference
- Remote Repositories v0.28.0 + GitHub Repositories v0.50.0
- Remote Repositories v0.29.2023020701 + GitHub Repositories v0.51.2023020701

same result:
![image](https://user-images.githubusercontent.com/18366087/217207489-32ac3125-7434-4167-ac23-e0636f15a6ee.png)

should i open a new issue?
