### ISSUE TITLE
Can not use `Open Remote Repository`

### ISSUE THREAD

**Issue by cary-hu** [microsoft/vscode-remote-repositories-github#297]
All the way try to open remote repository, will show this error:

![image](https://user-images.githubusercontent.com/41052104/216482584-f1763ecd-7591-4388-9347-7795f82667f7.png)

I tried: 
- ![image](https://user-images.githubusercontent.com/41052104/216482764-415283b5-7fbc-4a66-9088-4f7db7b5e8dc.png)
- ![image](https://user-images.githubusercontent.com/41052104/216482776-71b7d37b-7064-4856-b7dd-ce8da4353703.png)

Env:
```
Version: 1.74.3 (user setup)
Commit: 97dec172d3256f8ca4bfb2143f3f76b503ca0534
Date: 2023-01-09T16:59:02.252Z (3 wks ago)
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: No
```

Extension: 
![image](https://user-images.githubusercontent.com/41052104/216483993-97cffef8-5c28-4c37-9ebd-127a0ae0fc17.png)

**Comment by joyceerhl** [comment]
@cary-hu what version of VS Code, the Remote Repositories extension, and the GitHub Repositories extension are you using?

**Comment by cary-hu** [comment]
Added more info about my env

**Comment by cary-hu** [comment]
Just secs ago, vscode update, and the extension works, now, my env:

```
Version: 1.75.0 (user setup)
Commit: e2816fe719a4026ffa1ee0189dc89bdfdbafb164
Date: 2023-02-01T15:23:45.584Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: No
```

**Comment by FahadBinHussain** [comment]
Yeah, after vscode update it works

**Comment by GeorgeHcc** [comment]
@joyceerhl the same problem with me 

my env:

Version: 1.79.2 (system setup)
Commit: 695af097c7bd098fbf017ce3ac85e09bbc5dda06
Date: 2023-06-14T08:57:04.379Z
Electron: 22.5.7Date
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19045
Sandboxed: undefined

**Comment by joyceerhl** [comment]
@GeorgeHcc can you please provide a screen recording of the behavior you're seeing?
