### ISSUE TITLE
Pull Request to someone else's repo

### ISSUE THREAD

**Issue by jibbers42** [microsoft/vscode-remote-repositories-github#3]
I need to change one word in another repo and submit a PR. I decided to try remote repositories since this seems like a perfect use case, but I'm having trouble finding the right process. Is there a simple flow for this?

1. I opened their repo in vscode.
1. I changed the wrong property accessor to the correct one.
1. I try to fork at this point, but don't see a way. I'm not allowed to branch since I'm on their repo.
1. I type in a commit message and commit (via checkbox icon) - vscode prompts me to fork. I do.
1. The Source Control view is pretty empty. I see no history at all and can't find a way to open that pane.
1. I'm not sure where my commit is.
1. I find the Remote Explorer.
  1. Why are there two "master" branches?
  1. Why does it say there are "Uncommitted Changes" (and where is my commit)?
  1. I right-click on the inner most item (System.Diagnostics.Abstractions/Process...) and take a chance on "Apply Changes".
![image](https://user-images.githubusercontent.com/797824/121625300-3113d380-ca41-11eb-8129-34aaa6bb2336.png)
1. Now I have a modified file (my original change).
1. I save it and it shoes as modified in the Source Control view.
1. I decide to create a branch for the PR. When I try to switch to the branch I get a warning that my uncommitted changes won't be visible.
1. I figure what-the-heck and do it anyway since I need the branch for the PR... the changes are still there. (phew!)
1. I stage and commit my change again.
1. I still see no history in Source Control view.
1. I hit "Create a Pull Request" and vscode says "There are no changes"
1. Still not sure where my commit is.
1. I give up at this point and look in github. I see the new branch with the commit (and an extra blank commit?). I'll do the PR from there.

I banged this out pretty quickly and don't mean to downplay any hard work that was put into this feature. This is a pretty great feature really, but I don't really understand it I think, and/or maybe it's just intended for working on your own repo. I'm not sure, but I think it would be great if the creating simple PRs to another owners repo was a bit easier to figure out.

**Comment by jibbers42** [comment]
After reading it over, I see that I should have realized my commit was directly in GItHub; however, I think the blank Source Control view really threw me off - along with a couple other points of confusion in the UI. Also, unless I'm just missing it, I still don't see the "simple" way to do a quick PR against someone else's repo.

**Comment by brettcannon** [comment]
I tried a similar thing today, except I:

1. Went straight to my fork of the repo
2. Had GitHub update my fork through the web
3. Opened my fork in Remote Repositories
4. Created a new branch
5. Made my change
6. Committed it
7. ... couldn't find a way to open a PR

In the end I created the PR via the web but I was expecting some way to do it in VS Code itself.

**Comment by joyceerhl** [comment]
The simple way to PR to someone else's repo is as follows:

1. Start on the main branch of a repo 
2. Make your changes
3. Commit directly 
4. At this point you should be prompted to create a fork, commit your changes to a new branch, and create a PR for that branch.
