### ISSUE TITLE
how do I change the branch?

### ISSUE THREAD

**Issue by kkkkh** [microsoft/vscode-remote-repositories-github#300]
how do I change the branch? I wonder if this feature has been developed

**Comment by joyceerhl** [comment]
From the status bar, you can open the branch picker and select a different branch to open.

![image](https://user-images.githubusercontent.com/30305945/219102131-98c6bd1c-2a5d-4a67-ae3b-576d69a27f23.png)
![image](https://user-images.githubusercontent.com/30305945/219102217-626dfc41-0c3d-45c2-84d9-cc704f6c7635.png)
