### ISSUE TITLE
SCM/statusbar (and api events) aren't correct for a repo with no files open on load

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode-remote-repositories-github#308]
If you open a repo in vscode.dev or github.dev and there are no opened editors, the SCM view & statusbar aren't updated correctly -- e.g. the branch is missing. It seems to fix itself at some point if you just do nothing (takes like a minute or so -- or maybe its switching tabs and coming back) -- or if you open a file it will "fix" things too.

![image](https://user-images.githubusercontent.com/641685/222511953-94ef2050-fcfb-47db-927d-5adc506215e6.png)

This also causes GitLens to not detect that there is a repository open -- which seems like there is an event or timing issue missing.

**Comment by joyceerhl** [comment]
Closing as I have not seen this lately and there has been recent rework of the SCM view. Please reopen if this persists for you in latest Insiders!
