### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Ofeksh13** [microsoft/vscode-remote-repositories-github#316]
I have an iPod pro and i can’t compile and VS asks me to download a decoder for 
the c language and it doesn’t give anything on the device 
Any suggestions for solving the problem?

Version: 1.76.2
Commit: ee2b180d582a7f601fa6ecfdad8d9fd269ab1884
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.2 Safari/605.1.15
Embedder: vscode.dev

Extension version: 0.30.0

**Comment by joyceerhl** [comment]
vscode.dev doesn't currently support compiling C, please consider using [GitHub Codespaces](https://github.com/features/codespaces) or [Remote Tunnels](https://code.visualstudio.com/docs/remote/tunnels) if you would like to be able to compile in your browser.
