### ISSUE TITLE
Duplicate clone command

### ISSUE THREAD

**Issue by aetonsi** [microsoft/vscode-remote-repositories-github#318]
Hi
since @joyceerhl told me here: https://github.com/microsoft/vscode-remote-repositories-github/issues/294#issuecomment-1419397303 that having both the `Continue working in new local clone` and `Clone repository locally and open on desktop` commands together is a bug, i'm opening this issue.

I still see them both, even with the pre-release/preview version:
- Remote Repositories v0.32.0
- GitHub Repositories v0.55.2023033002

![image](https://user-images.githubusercontent.com/18366087/229135342-ea0c303a-2208-4381-be58-4c9960b75428.png)

---

have a nice day

**Comment by joyceerhl** [comment]
Will be fixed in next nightly build of the Remote Repos extension. Issue verification:
- Open a GitHub repo on desktop using the `Open Remote Repository` command
- Open the command palette and search for 'clone'
- There should only be one command

**Comment by aetonsi** [comment]
👍
