### ISSUE TITLE
[feat] Allow for owner → repo folder structure

### ISSUE THREAD

**Issue by aetonsi** [microsoft/vscode-remote-repositories-github#319]
Hi
it would be nice if there was a feature (a simple boolean) to allow for locally cloning repos into subfolders with the repo's author/owner username.
At the moment, when you `continue to work in local clone`, you get asked for the folder that will contain the cloned repo.
Then, if you clone:
- [php-src](https://github.com/php/php-src/)
- [ramsey/**collection**](https://github.com/ramsey/collection)
- [ramsey/uuid](https://github.com/ramsey/uuid)
- [aetonsi/rclapper](https://github.com/aetonsi/rclapper)

You will get the folder structure:
```
<root>
↳ php-src
↳ collection
↳ uuid
↳ rclapper
```

A part from the fact that multiple users might have repos with the same name ([ramsey/**collection**](https://github.com/ramsey/collection), [loophp/**collection**](https://github.com/loophp/collection), [chenhg5/**collection**](https://github.com/chenhg5/collection)).. A part from that, you will still have no idea which repo it is exactly, unless you remember the owner by heart, or run `git remote -v`.

With a simple setting `Create repo owner parent  folder when cloning` (or something like that), when cloning you will still be asked for the container/root folder, but then an intermediate folder named like the repo's owner will be created, like this:
```
<root>
↳ php
   ↳ php-src
↳ ramsey
   ↳ collection
   ↳ uuid
↳ aetonsi
   ↳ rclapper
```

This way you can precisely identify each repo (and have [as many `collection`s](https://github.com/search?q=%22collection%22+in%3Aname&type=repositories) as you'd like)

---

thank your for your attention

**Comment by aetonsi** [comment]
(sorry i submitted an empty post by mistake)

**Comment by joyceerhl** [comment]
Closing this since there hasn't been feedback from additional users that this functionality would be useful.
