### ISSUE TITLE
Unable to commit

### ISSUE THREAD

**Issue by chirag-droid** [microsoft/vscode-remote-repositories-github#32]
So I opened this repo in my [chirag-droid/github-actions-demo](https://github.com/chirag-droid/github-actions-demo) in Remote Repositories.

Edit: The error mostly happens inside the .github directory specifically

1. I made a workflows directory inside the .github directory.
2. Then I created a new file called `github-actions-demo.yml` inside the workflows directory.
3. I staged the changes and then tried to commit but the commit failed.
4. On refreshing the files, `github-actions-demo.yml` is gone and making file with the same name shows error.
5. Now I can't commit it, neither can I discard the changes or remove the workflows dir or create a new file with the same name. Its stuck!

https://user-images.githubusercontent.com/81347541/125171366-7dce0400-e1d1-11eb-8734-9663b48ad403.mp4

I don' t really know what caused the issue. I repeated this process several times still the same result.

**Comment by chirag-droid** [comment]
This is my Github issue please let me know if i missed something :p

**Comment by eamodio** [comment]
Can you try this again with the latest version of _Remote Repositories_ -- a new version was just released today. If that still fails, please enable debug logging by running from _Remote Repositories: Enable Debug Logging_ from the command palette (`ctrl+shift+p` or `cmd+shift+p`). This will enable logging to the _Remote Repositories_ channel in the _Output_ pane.

Once enabled, please reproduce the issue, and attach the log from the _Remote Repositories_ channel.

**Comment by chirag-droid** [comment]
I updated to the latest version, still get the same error
<details open>
<summary>Here is the log:</summary>

- [2021-07-09 19:02:42:701] [  473] (A) Reader(226|vscode-vfs://github/chirag-droid/github-actions-demo) • ChangeStore.hasMergeConflicts(vscode-vfs://github/chirag-droid/github-actions-demo)
- [2021-07-09 19:02:42:701] [  473] (L) Reader(226|vscode-vfs://github/chirag-droid/github-actions-demo) waited for 0 ms • ChangeStore.hasMergeConflicts(vscode-vfs://github/chirag-droid/github-actions-demo)
- [2021-07-09 19:02:42:702] [  473] (U) Reader(226|vscode-vfs://github/chirag-droid/github-actions-demo) locked for 0 ms • ChangeStore.hasMergeConflicts(vscode-vfs://github/chirag-droid/github-actions-demo)
- [2021-07-09 19:02:42:702] [  474] (A) Reader(227|vscode-vfs://github/chirag-droid/github-actions-demo) • ChangeStore.getStagedChanges(vscode-vfs://github/chirag-droid/github-actions-demo)
- [2021-07-09 19:02:42:702] [  474] (L) Reader(227|vscode-vfs://github/chirag-droid/github-actions-demo) waited for 0 ms • ChangeStore.getStagedChanges(vscode-vfs://github/chirag-droid/github-actions-demo)
- [2021-07-09 19:02:42:702] [  474] (U) Reader(227|vscode-vfs://github/chirag-droid/github-actions-demo) locked for 0 ms • ChangeStore.getStagedChanges(vscode-vfs://github/chirag-droid/github-actions-demo)
- [2021-07-09 19:02:42:702] [  475] (A) Reader(228|vscode-vfs://github/chirag-droid/github-actions-demo) • ChangeStore.getContent(vscode-vfs://github/chirag-droid/github-actions-demo/.github/workflows/lint.yml}
- [2021-07-09 19:02:42:702] [  475] (L) Reader(228|vscode-vfs://github/chirag-droid/github-actions-demo) waited for 0 ms • ChangeStore.getContent(vscode-vfs://github/chirag-droid/github-actions-demo/.github/workflows/lint.yml}
- [2021-07-09 19:02:42:703] [  476] ExtFileStorageService.get(changestore/vscode-vfs-github/chirag-droid/github-actions-demo/.github/workflows/lint.yml): scopedKey=073e725beac3d7e2fe3002bac8d0a22d/changestore/vscode-vfs-github/chirag-droid/github-actions-demo/.github/workflows/lint.yml
- [2021-07-09 19:02:42:719] [  476] ExtFileStorageService.get(changestore/vscode-vfs-github/chirag-droid/github-actions-demo/.github/workflows/lint.yml): scopedKey=073e725beac3d7e2fe3002bac8d0a22d/changestore/vscode-vfs-github/chirag-droid/github-actions-demo/.github/workflows/lint.yml • took 16 ms
- [2021-07-09 19:02:42:719] [  475] (U) Reader(228|vscode-vfs://github/chirag-droid/github-actions-demo) locked for 16 ms • ChangeStore.getContent(vscode-vfs://github/chirag-droid/github-actions-demo/.github/workflows/lint.yml}
- [2021-07-09 19:02:48:321] c:\Users\Karnu\.vscode\extensions\github.remotehub-0.11.0\dist\extension.js:107:24384
HttpError: Not Found
- [2021-07-09 19:02:48:321] c:\Users\Karnu\.vscode\extensions\github.remotehub-0.11.0\dist\extension.js:107:24384
HttpError: Not Found

</details>

**Comment by eamodio** [comment]
@chirag-droid Hrm, I'm still at a loss as I don't see any errors or anything. Can you capture a video/gif of what you are doing/seeing?

**Comment by chirag-droid** [comment]
Here you go. I cant do commit of nested files. This doesn't happen with other repo, I also tried discarding all changes.

https://user-images.githubusercontent.com/81347541/125171366-7dce0400-e1d1-11eb-8734-9663b48ad403.mp4

Didn't happen with this repo:

https://user-images.githubusercontent.com/81347541/125171462-0056c380-e1d2-11eb-9679-cb9310f85a86.mp

**Comment by chirag-droid** [comment]
I tried commiting in .github in repo at second video, the same error showed. So the error only happens in .github dir specifically.

**Comment by eamodio** [comment]
This is resolved in the latest GitHub Repositories (Insiders)
