### ISSUE TITLE
Compatibility with Azure Data Studio

### ISSUE THREAD

**Issue by hucksy** [microsoft/vscode-remote-repositories-github#325]
Hi,

I'd like to request this extension to be made compatible with Azure Data Studio, if that's possible. Currently I don't know of any extensions that allow a user to access Azure Devops Server / TFS within Azure Data Studio. My internet searches seem to show that this was possible at one point, but it's no longer possible with current releases.

Thanks!

**Comment by joyceerhl** [comment]
Hi, thanks for opening an issue! Please consider filing this as a feature request for Azure Data Studio, as we (VS Code) can't guarantee compatibility with ADS. Thank you for your time.

**Comment by anguswilliams93** [comment]
Bump
