### ISSUE TITLE
I think there still might be something up here:

### ISSUE THREAD

**Issue by Amalahnd** [microsoft/vscode-remote-repositories-github#327]
I think there still might be something up here:

1. Open an empty window
2. "Open remote repository"
3. Enter `owner/repo` for something you don't have write access and thus isn't in the picker
4. Selecting the "Enter a Remote URL" does nothing

<img width="631" alt="image" src="https://user-images.githubusercontent.com/2230985/234723066-007746e9-6744-48af-b149-0bf731400a0b.png">

I would expect that action to work, or for there to be some action like "Open nodejs/node from GitHub"

However the "js-debug wasn't there" problem does appear to be fixed 🙂

_Originally posted by @connor4312 in https://github.com/microsoft/vscode-remote-repositories-github/issues/219#issuecomment-1524178807_

**Comment by joyceerhl** [comment]
Duplicate https://github.com/microsoft/vscode-remote-repositories-github/issues/264
