### ISSUE TITLE
Is it possible to add support for commit signing?

### ISSUE THREAD

**Issue by ridays2001** [microsoft/vscode-remote-repositories-github#33]
[Feature Request]
Hello,
Is it possible to enable support for commit signing via gpg or via GitHub?
I loved the concept of working with repositories without the need of cloning them, but I'm pretty sure a lot of repositories require the committer to sign their commits to verify the authenticity of code. From what I understand, there are only 2 ways to get verified commits - either to make them on GitHub or to sign them manually using gpg keys.

**Comment by eamodio** [comment]
We would like to support this scenario.

**Comment by joyceerhl** [comment]
Beginning with tonight's Insiders, you can set `"remoteHub.experimental.graphql.createCommitOnBranch": true` in your settings.json to get commit signing for all commits created through the GitHub Repositories extension. This is achieved using the [GitHub GraphQL `createCommitOnBranch` API](https://github.blog/changelog/2021-09-13-a-simpler-api-for-authoring-commits/). Please let us know if you notice any issues.
