### ISSUE TITLE
SCM view fails to reflect changes after committing changes to a GitHub repo on insiders.vscode.dev

### ISSUE THREAD

**Issue by bhavyaus** [microsoft/vscode-remote-repositories-github#342]
The SCM View buttons also become unresponsive after the first attempt at staging and commiting. The changes are however commited to github.com
I also lose the branch picker.

<img width="811" alt="image" src="https://github.com/microsoft/vscode-remote-repositories-github/assets/25044782/bbc0375a-cd14-4fac-a9b6-43a1b80243f3">

**Comment by joyceerhl** [comment]
@bhavyaus are there any error messages in the developer tools log when the branch picker disappears (and does it disappear after committing)?

**Comment by joyceerhl** [comment]
This is a performance regression that is attributable to the rich nav endpoint taking upwards of a minute to return 404 responses when we request specific snapshots.

Workaround is to set `"remoteHub.richNavigation.enabled": false`.

**Comment by dbaeumer** [comment]
Got fixed and merged into main.

**Comment by joyceerhl** [comment]
@dbaeumer thank you!
