### ISSUE TITLE
live share is not happening

### ISSUE THREAD

**Issue by Machi2130** [microsoft/vscode-remote-repositories-github#345]
Type: <b>Bug</b>

am not able to live share 

Extension version: 0.58.0
VS Code version: Code 1.79.2 (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:57:04.379Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-11320H @ 3.20GHz (8 x 3187)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.79GB (0.69GB free)|
|Process Argv|C:\\Users\\Harshada\\Desktop\\Calculater\\main.js --crash-reporter-id 59172619-ac76-4b35-b232-1a85002c6723|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30776702
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30610679
282f8724:30602487
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
a9j8j154:30646983
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
a2ce3375:30757347
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
hideindicator:30766889
pythongtdpath:30769146
bgfeh915:30780428
pythonnosmt12:30779714
pythonidxptcf:30772540
pythonnocebcf:30776496

```

</details>

**Comment by joyceerhl** [comment]
@Machi2130 can you please share what version of the Live Share extension you are using? Are there any errors that you see in the Window output channel?

**Comment by SomyaAgr** [comment]
> @Machi2130 can you please share what version of the Live Share extension you are using? Are there any errors that you see in the Window output channel?

hey i m also facing same problem while i am using remote repository extension i cant using live server it is disable also 

![image](https://github.com/microsoft/vscode-remote-repositories-github/assets/91428207/4ab6af65-52f5-48f2-a1da-229b202d9701)

Thanks in advance 
somya

**Comment by joyceerhl** [comment]
Hi @somyaagr, this issue is about [Live Share](https://marketplace.visualstudio.com/items?itemName=MS-vsliveshare.vsliveshare) and not Live Server. Please file an issue for the Live Server extension instead to ask that they support virtual workspaces, thanks! https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer

**Comment by SomyaAgr** [comment]
Hey so sorry for that
