### ISSUE TITLE
GitHub Remote Repositories throwing error on MacOS when accessing Repositories

### ISSUE THREAD

**Issue by AshuMaster** [microsoft/vscode-remote-repositories-github#348]
When trying to use Remote Repositories in VSCode, I get this error:

Steps to Reproduce:

1. Open Remote Explorer
2. Click Open Remote Repository

Error on the Popup:
Error running command remoteHub.openRepository: n.provider.getRemoteSourceProviders is not a function. This is likely caused by the extension that contributes remoteHub.openRepository.

![Screenshot](https://github.com/microsoft/vscode-remote-repositories-github/assets/106397875/f7716862-785e-4b04-8b14-5c27e50bb65c)

**Comment by joyceerhl** [comment]
@ashumaster do you have the latest version of the [GitHub Repositories extension](https://marketplace.visualstudio.com/items?itemName=github.remotehub) installed and enabled?

**Comment by Arturik2011** [comment]
> When trying to use Remote Repositories in VSCode, I get this error:
> 
> 
> 
> Steps to Reproduce:
> 
> 
> 
> 1. Open Remote Explorer
> 
> 2. Click Open Remote Repository
> 
> 
> 
> Error on the Popup:
> 
> Error running command remoteHub.openRepository: n.provider.getRemoteSourceProviders is not a function. This is likely caused by the extension that contributes remoteHub.openRepository.
> 
> 
> 
>prizes 100k
4000$
{$$$}}}}}}
Papa
100 000 $$$

**Comment by Arturik2011** [comment]
> When trying to use Remote Repositories in VSCode, I get this error:
> 
> 
> 
> Steps to Reproduce:
> 
> 
> 
> 1. Open Remote Explorer
> 
> 2. Click Open Remote Repository
> 
> 
> 
> Error on the Popup:
> 
> Error running command remoteHub.openRepository: n.provider.getRemoteSourceProviders is not a function. This is likely caused by the extension that contributes remoteHub.openRepository.
> 
> 
> 
> ![Screenshot](https://github.com/microsoft/vscode-remote-repositories-github/assets/106397875/f7716862-785e-4b04-8b14-5c27e50bb65c)

**Comment by AshuMaster** [comment]
Yes @joyceerhl I am using the latest version of the [GitHub Repositories extension](https://marketplace.visualstudio.com/items?itemName=github.remotehub).

**Comment by AshuMaster** [comment]
I tried using the same setup in Windows and it's working perfectly. I think it's only showing the error message on the macOS. The above Error screenshot is from the Mac system.

**Comment by joyceerhl** [comment]
Do you have 0.38.1 of Remote Repositories?

**Comment by Arturik2011** [comment]
> I tried using the same setup in Windows and it's working perfectly. I think it's only showing the error message on the macOS. The above Error screenshot is from the Mac system.

**Comment by Arturik2011** [comment]
> When trying to use Remote Repositories in VSCode, I get this error:
> 
> 
> 
> Steps to Reproduce:
> 
> 
> 
> 1. Open Remote Explorer
> 
> 2. Click Open Remote Repository
> 
> 
> 
> Error on the Popup:
> 
> Error running command remoteHub.openRepository: n.provider.getRemoteSourceProviders is not a function. This is likely caused by the extension that contributes remoteHub.openRepository.
> 
> 
> 
> ![Screenshot](https://github.com/microsoft/vscode-remote-repositories-github/assets/106397875/f7716862-785e-4b04-8b14-5c27e50bb65c)

**Comment by jrdodds** [comment]
FWIW I tried to reproduce this error and I couldn't.

macOS Monterey 12.6.7

Name: Azure Repos
Id: ms-vscode.azure-repos
Description: Remotely browse and edit any Azure Repos
Version: 0.36.0
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-vscode.azure-repos

VSCode:
Version: 1.80.1 (Universal)
Commit: 74f6148eb9ea00507ec113ec51c489d6ffb4b771
Date: 2023-07-12T17:20:23.298Z
Electron: 22.3.14
ElectronBuildId: 21893604
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 21.6.0

**Comment by AshuMaster** [comment]
My apologies for the oversight. I'm pleased to let you know that the problem has been resolved. The error was caused due to my VS Code not being the latest version on macOS. After updating VS Code to the latest version, the Azure Repos Extension, and GitHub Repositories Extension also got updated to version v0.36.0 and v0.60.0. Previously, I was using an older version of Extensions. Now, after the update, everything is working perfectly.
