### ISSUE TITLE
TFVC - it's non-obvious that TFVC is not supported

### ISSUE THREAD

**Issue by jrdodds** [microsoft/vscode-remote-repositories-github#350]
Currently TFVC is not supported. Is there a plan to support TFVC repos in the **Azure Repos** extension?

There are several issues with the current situation where TFVC is not supported.

### Doc Issue: Marketplace description is not correct
The Marketplace description of the **Azure Repos** extension states:

> The **Azure Repos extension** lets you quickly browse and search _**any remote Azure Repos repository**_ [emphasis added] directly from within Visual Studio Code.

The Repos service of Azure DevOps supports git and TFVC repos therefore this description says that TFVC repos are supported, which is not the case.

Changing to 

"The **Azure Repos extension** lets you quickly browse and search a remote Azure Repos git repository ..."

would address the issue.

### Selecting a repo
The "Open Remote Repository" picker shows only git repos.

For a project with a TFVC repo and one or more git repos, the picker will have a drop-down list with the names of the git repos. Because only the git repos show up, one can hazard a guess that the TFVC repos are not being listed.

For a project with only a TFVC repo, the picker has no drop-down list. If you are not familiar with the extension and don't know that TFVC is not supported, it appears that the extension doesn't work.

Visual feedback in the UI that the TFVC repo exists but can't be opened would be helpful.

**Comment by jrdodds** [comment]
No changes made for this?

**Comment by joyceerhl** [comment]
Next pre-release (and the upcoming January stable release) will have an updated README clarifying we only support git repos.

**Comment by shishini** [comment]
I was hurt by this today, its still not obvious that tfvc repos are not supported 
I think the plugin should be renamed to Azure Git Repos
