### ISSUE TITLE
PHPserver / Liveserver

### ISSUE THREAD

**Issue by djansen1987** [microsoft/vscode-remote-repositories-github#355]
Great idee, but not working for me. I am getting it not to work with other extentions to live preview for example php/html before committing. I think this is because it only downloads the file your edititing and the location was also hard to find C:\Users\user\AppData\Roaming\Code\User\globalStorage\github.remotehub\xxx\xxx\x.php

reverting to github desktop app

**Comment by joyceerhl** [comment]
Duplicate https://github.com/microsoft/vscode-livepreview/issues/190

**Comment by joyceerhl** [comment]
If you want to use Live Preview and PHPserver with downloaded files, you can always use the builtin git extension to clone your desired files
