### ISSUE TITLE
Feature Request: Copy Azure Repos link to code selection

### ISSUE THREAD

**Issue by thegoatherder** [microsoft/vscode-remote-repositories-github#359]
Azure Repos web browser version has a feature to share a link to highlighted lines of code:

![image](https://github.com/microsoft/vscode-remote-repositories-github/assets/389668/e6694f42-9854-4f97-8852-a127641e676d)

As an Azure Repos and VS Code user, I want to send a link to a line or lines of code highlighted in VS Code to another Azure Repos user without visiting Azure Repos in a web browser.

Ideally, when creating the link in VSCode there would be 2 command options:
1. Generate link to code on Azure Repos (web version)
2. Generate link to code directly in VSCode (for link recipients with the remote repos extension installed)

**Comment by joyceerhl** [comment]
The second option is available via the Copy vscode.dev Link command, which is in both the command palette and also in the line number context menu:

![image](https://github.com/microsoft/vscode-remote-repositories-github/assets/30305945/5047405d-c2c7-4aa4-b726-9f4b632aa93a)

The first option is not yet available.

**Comment by lszomoru** [comment]
Since the ability to share a vscode.dev link is available, I will go ahead and close this feature request.
