### ISSUE TITLE
clonar repositorio

### ISSUE THREAD

**Issue by boludoz** [microsoft/vscode-remote-repositories-github#365]
Type: <b>Bug</b>

no me deja clonar repositorios que es lo unico que me interesa, me compre un ordenador de 1000 dolares para tener los archivos en mi disco duro.

Extension version: 0.38.1
VS Code version: Code 1.82.0 (8b617bd08fd9e3fc94d14adb8d358b56e3f72314, 2023-09-06T22:07:07.438Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by joyceerhl** [comment]
The builtin VS Code git extension allows you to clone repos once you have installed git.
