### ISSUE TITLE
Can't automatically update the branch list 

### ISSUE THREAD

**Issue by finalwhy** [microsoft/vscode-remote-repositories-github#37]
When I delete a branch on github, this plugin cannot automatically update my branch list
![Code_kiCDgZHC5G](https://user-images.githubusercontent.com/24859256/124929721-4de8fa00-e033-11eb-901c-7286223b5067.png)

**Comment by eamodio** [comment]
In the latest version `0.11.0` there is now an option to remove remote repository branches from that UI -- right-click and choose _Remove_.
