### ISSUE TITLE
Extension activation failed

### ISSUE THREAD

**Issue by terashy88** [microsoft/vscode-remote-repositories-github#370]
Type: <b>Bug</b>

Error: Extension 'ms-vscode.remote-repositories' CANNOT use API proposal: shareProvider.
Its package.json#enabledApiProposals-property declares: contribEditSessions, contribRemoteHelp, contribMenuBarHome, contribViewsRemote, contribViewsWelcome, contribShareMenu, documentFiltersExclusive, editSessionIdentityProvider, extensionRuntime, fileSearchProvider, quickPickSortByLabel, workspaceTrust, scmActionButton, scmSelectedProvider, scmValidation, textSearchProvider, timeline but NOT shareProvider.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api ms-vscode.remote-repositories

Extension version: 0.38.1
VSCodium version: VSCodium 1.82.2 (a5004432af6600c99fa4f918a3f2f8df44df71e6, 2023-09-14T18:27:11.315Z)
OS version: Linux x64 6.5.1-1-MANJARO
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2700)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|6, 4, 3|
|Memory (System)|30.98GB (18.56GB free)|
|Process Argv|--ms-enable-electron-run-as-node --no-sandbox --unity-launch --enable-proposed-api genuitecllc.codetogether|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|xfce|
|XDG_CURRENT_DESKTOP|XFCE|
|XDG_SESSION_DESKTOP|xfce|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by joyceerhl** [comment]
This looks like an issue with VSCodium itself, please file an issue there
