### ISSUE TITLE
点击没反应

### ISSUE THREAD

**Issue by XAJ-Code** [microsoft/vscode-remote-repositories-github#378]
Type: <b>Bug</b>

已经安装了该扩展，左边菜单栏也显示图标了，点击打开远程存储库没反应，也没有任何提示，也重启过编辑器试过

Extension version: 0.32.0
VS Code version: Code 1.77.1 (b7886d7461186a5eac768481578c1d7ca80e2d21, 2023-04-04T23:21:11.906Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i5-12400 (12 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.78GB (11.15GB free)|
|Process Argv|--crash-reporter-id 19f4a46f-ae66-4028-a9e8-29943905eb1a|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263cf:30856253
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
f6dab269:30613381
showlangstatbar:30737416
0bi6i642:30841073
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
dsvsc015:30845448
pyreplss1:30865275
pythontbext0:30864172

```

</details>

**Comment by joyceerhl** [comment]
Do you have the GitHub Repositories extension installed? https://marketplace.visualstudio.com/items?itemName=github.remotehub

**Comment by x-wink** [comment]
> Do you have the GitHub Repositories extension installed? https://marketplace.visualstudio.com/items?itemName=github.remotehub

same question
I installed GitHub Repositories extension

system info
```
CPUs | Intel(R) Xeon(R) CPU E5-2673 v3 @ 2.40GHz (24 x 2394)
-- | --
GPU Status | 2d_canvas: enabled canvas_oop_rasterization: disabled_off direct_rendering_display_compositor: disabled_off_ok gpu_compositing: enabled multiple_raster_threads: enabled_on opengl: enabled_on rasterization: enabled raw_draw: disabled_off_ok skia_renderer: enabled_on video_decode: enabled video_encode: enabled vulkan: disabled_off webgl: enabled webgl2: enabled webgpu: disabled_off
Load (avg) |  
Memory (System) | 31.86GB (22.02GB free)
Process Argv | --crash-reporter-id ccaee095-a0d4-4048-a97f-b0db1ea0787e
Screen Reader | no
VM | 0%
```

vscode info
```
版本: 1.77.3 (user setup)
提交: 704ed70d4fd1c6bd6342c436f1ede30d1cff4710
日期: 2023-04-12T09:16:02.548Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.19045
沙盒化: No
```

A/B info
```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30856252
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
f6dab269:30613381
showlangstatbar:30737416
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
synctok:30869157
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30871694
pythonregdiag2:30871582
pyreplss1:30865275
pythonmypyd1:30859726
pythoncet00cf:30874137
pythontbext0:30864172
```

**Comment by joyceerhl** [comment]
@x-wink the latest stable VS Code version is 1.84, please try upgrading and let us know if you still repro

**Comment by x-wink** [comment]
it's already latest version, no upgrade tips and no way to check update, only can check ext's update
I download installer from website and reinstall, this probloem has been solved.
thanks!

**Comment by 0x01L** [comment]
the same issue
If I disable "GitHub Repositories", then "Remote Repositories" will show me the dialog and let me to input the URL or select "Open Repositories from GitHub", and I can search repositories, but it cannot be opened because the "GitHub Repositories" extension was  disabled.
If I enable "GitHub Repositories", then nothing happens after I clicked "Open Remote Repositories"

**Comment by x-wink** [comment]
upgrade vscode to latest version，if can't update uninstall and download.发自我的 iPhone在 2024年6月4日，19:33，0x01L ***@***.***> 写道：﻿
the same issue
If I disable "GitHub Repositories", then "Remote Repositories" will show me the dialog and let me to input the URL or select "Open Repositories from GitHub", and I can search repositories, but it cannot be opened because the "GitHub Repositories" extension was  disabled.
If I enable "GitHub Repositories", then nothing happens after I clicked "Open Remote Repositories"
