### ISSUE TITLE
Extension activation failed

### ISSUE THREAD

**Issue by lilsunny243** [microsoft/vscode-remote-repositories-github#384]
Type: <b>Bug</b>

Error: a provider for the scheme 'github' is already registered

Extension version: 0.62.0
VS Code version: Code - Insiders 1.84.0-insider (4678919d52909efc7c4ab958a2e5c8f45d50ffc3, 2023-10-13T05:44:50.546Z)
OS version: Darwin arm64 23.1.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|13, 13, 12|
|Memory (System)|8.00GB (0.11GB free)|
|Process Argv|--crash-reporter-id bcdb2890-4f42-4c88-9bce-0e884d7d2b99|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
vsc_aa:30263845
pythonptprofiler:30281269
vshan820:30294714
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
py29gd2263:30784851
vscaac:30438845
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pynewext54:30618038
showlangstatbar:30737417
pythonfmttext:30716741
fixshowwlkth:30771523
showindicator:30805243
pythongtdpath:30726887
i26e3531:30792625
pythonnosmt12:30779711
pythonidxpt:30768918
pythonnoceb:30776497
synctok:30869157
dsvsc013:30777762
dsvsc014:30777825
pythonmpswarning:30859870
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30871582
pyreplss1:30865275
pythonmypyd1:30859725
pythoncet0:30859736
pythontbext0cf:30864173

```

</details>

**Comment by joyceerhl** [comment]
@lilsunny243 could you please share which extensions you have installed?
