### ISSUE TITLE
Unable to Open Repository from Azure DevOps

### ISSUE THREAD

**Issue by mikew3432** [microsoft/vscode-remote-repositories-github#385]
Hello dear reader - this is a networking-caused issue but hard to fathom and hoping for assistance. It is probably an error handling bug? 

I go to Open Remote Repository and Open Repository from Azure Repos, the Azure Active Directory Tenant picker is not displayed - and goes straight to an empty Azure DevOps Organization picker. 

The catch is - this only happens connected on our new VPN. The problem is, how to determine what is broken. The network appliance logs are (too) abundantly full of successful connections... The root cause is undoubtedly some network/security policy, it works fine on our old VPN. However I'm finding it hard to troubleshoot and the network flow is not documented afaik.

Issue in pictures:

![image](https://github.com/microsoft/vscode-remote-repositories-github/assets/118790616/5c3777b2-ef39-4514-836c-fe7e9dd07b7e)
![image](https://github.com/microsoft/vscode-remote-repositories-github/assets/118790616/ac4b1604-75dd-4160-bb0b-80f6ac708173)
![image](https://github.com/microsoft/vscode-remote-repositories-github/assets/118790616/e73afdbd-e6fd-4fd6-8a71-3e294cfbde85)

<-- normally at this point in the sequence, I would get shown a couple of AAD tenant IDs, however it skips it -->

![image](https://github.com/microsoft/vscode-remote-repositories-github/assets/118790616/77ee5739-fbb0-4cf3-b4d2-65c03d763f7c)
^^^ Unable to open a Azure DevOps repo.

**Comment by mikew3432** [comment]
@lszomoru @joyceerhl This issue has progressed - not quite to a happy conclusion,

In testing with our vendors, we learned that on our new SASE solution we are doing https decryption and inspection on more internet URLs including where we previously we were not - due to our company threat protection policy and application of security vendor best practices.

To make VS Code Remote Repository to Azure DevOps work, we applied a very large number of exceptions to https decryption, based on this Microsoft page: https://learn.microsoft.com/en-us/azure/devops/organizations/security/allow-list-ip-url?view=azure-devops&tabs=IP-V4 

We have not narrowed it down any further as yet.

*** Typically issues like this are TLS certificate trust - where our internally trusted certificate is not trusted. Anyway where there is an issue, the client (normally a browser) will report the issue and we can resolve it.

However in this case the client is VS Code extension, and the extension does not report an issue - it just silently fails.  

We currently don't actually know a precise fix for it, just a shotgun of exceptions that is not ideal. Https decryption and inspection is a critical plank of our security infrastructure.

Can the VS Code and/or extension logging and/or error presentation to the user be improved?

**Comment by lszomoru** [comment]
@mikew3432, could you check the "Azure Repos" output channel to see if there are any errors there? 
You can access that by using the View -> Output menu, and then in the channel dropdown pick "Azure Repos". Thanks!

**Comment by mikew3432** [comment]
Thank you @lszomoru! that is very helpful.
![image](https://github.com/microsoft/vscode-remote-repositories-github/assets/118790616/9501db92-e3a9-40ee-9130-6522af7f75ca)
2023-12-06 16:00:04.444 [info] [    2] ChangeStore.getWorkspacesWithChanges()
2023-12-06 16:00:04.445 [info] [    2] ChangeStore.getWorkspacesWithChanges() took 0 ms
2023-12-06 16:00:06.064 [info] [    5] AzDO.ensureAuthenticated
2023-12-06 16:00:07.056 [warning] [    5] AzDO.ensureAuthenticated took 991 ms
2023-12-06 16:00:07.057 [info] [    6] AzDO.ensureAuthenticated
2023-12-06 16:00:07.193 [error] ClientRequest.<anonymous>
FetchError: request to https://app.vssps.visualstudio.com/_apis/profile/profiles/me?api-version=7.0 failed, reason: unable to get issuer certificate
2023-12-06 16:00:07.194 [error] ClientRequest.<anonymous>
FetchError: request to https://app.vssps.visualstudio.com/_apis/profile/profiles/me?api-version=7.0 failed, reason: unable to get issuer certificate

We can use this info. Actually I didn't know about the Output panels. Much appreciated.

**Comment by lszomoru** [comment]
Glad the information is helpful. Please keep me posted on whether things will work out.

**Comment by Furka-090** [comment]
> Merhaba sevgili okuyucu - bu ağ kaynaklı bir sorundur ancak anlaşılması zordur ve yardım umuyorum. Muhtemelen bir hata işleme hatasıdır?
> 
> Uzak Depoyu Aç ve Azure Depolarından Depoyu Aç'a gidiyorum, Azure Active Directory Kiracı seçicisi görüntülenmiyor ve doğrudan boş bir Azure DevOps Kuruluş seçicisine gidiyor.
> 
> İşin püf noktası şu - bu yalnızca yeni VPN'imize bağlıyken gerçekleşiyor. Sorun, neyin bozulduğunu nasıl belirleyeceğimiz. Ağ cihazı günlükleri (çok) başarılı bağlantılarla dolu... Kök neden şüphesiz bir ağ/güvenlik politikası, eski VPN'imizde gayet iyi çalışıyor. Ancak sorun gidermeyi zor buluyorum ve bildiğim kadarıyla ağ akışı belgelenmemiş.
> 
> Resimli sorun:
> 
> ![görüntü](https://private-user-images.githubusercontent.com/118790616/278489964-5c3777b2-ef39-4514-836c-fe7e9dd07b7e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwODk5MjMsIm5iZiI6MTcyNzA4OTYyMywicGF0aCI6Ii8xMTg3OTA2MTYvMjc4NDg5OTY0LTVjMzc3N2IyLWVmMzktNDUxNC04MzZjLWZlN2U5ZGQwN2I3ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyM1QxMTA3MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZWU5MDgwNjU0ZTM2OTFiNTQ4ZThlMTJiNjVjOTkwYmYwOTVlM2Y0YzIwMzlmYzFiZjcxOTIxNDUxNTIxY2JkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.v4SykxWH3y8TBif6GuX3kX99VgaV16dDAd5NEWhWLn4) ![görüntü](https://private-user-images.githubusercontent.com/118790616/278489336-ac4b1604-75dd-4160-bb0b-80f6ac708173.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwODk5MjMsIm5iZiI6MTcyNzA4OTYyMywicGF0aCI6Ii8xMTg3OTA2MTYvMjc4NDg5MzM2LWFjNGIxNjA0LTc1ZGQtNDE2MC1iYjBiLTgwZjZhYzcwODE3My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyM1QxMTA3MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZTExMzNkOTQ0ZDYwZTIxNTI1YzNjYTZhNTdkOWUyZmYxM2RkZDE2ZDk2NGY5NjU4MTE0NmJkMTI3OTc4OGViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.TAOMX0Cn0fXsdZL61fWGHfAYTxx438VptvWrrh-hGw0) ![görüntü](https://private-user-images.githubusercontent.com/118790616/278489477-e73afdbd-e6fd-4fd6-8a71-3e294cfbde85.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwODk5MjMsIm5iZiI6MTcyNzA4OTYyMywicGF0aCI6Ii8xMTg3OTA2MTYvMjc4NDg5NDc3LWU3M2FmZGJkLWU2ZmQtNGZkNi04YTcxLTNlMjk0Y2ZiZGU4NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyM1QxMTA3MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNDJhMGJhNmUwMjk2Mjg5YjNiZWQ1M2M2NjAxMDgyNjkwMjkyYzliZDU1NzE5YTg3NDVlM2EzMTRjOTA2MDIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.iWej1lnvhVN-mQqtDs-tW5dawAzNUGqrm82cWcIRhXg)
> 
> <-- normalde dizinin bu noktasında, bana birkaç AAD kiracı kimliği gösterilirdi, ancak bunu atlıyor -->
> 
> ![görüntü](https://private-user-images.githubusercontent.com/118790616/278489656-77ee5739-fbb0-4cf3-b4d2-65c03d763f7c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwODk5MjMsIm5iZiI6MTcyNzA4OTYyMywicGF0aCI6Ii8xMTg3OTA2MTYvMjc4NDg5NjU2LTc3ZWU1NzM5LWZiYjAtNGNmMy1iNGQyLTY1YzAzZDc2M2Y3Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyM1QxMTA3MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYjk2ODdkNWQwMWViMTZiMzZiN2M1ODdiODY1M2U5NTM3ZTNjZDVmNmIyOGJhZDY4YzBhNDU1ODI0NzM2MjZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.DJDFyiFqAOxoql_b5FjkZcJRsbBFdeXgtW60h5JKFKg) ^^^ Azure DevOps deposu açılamıyor.
/
