### ISSUE TITLE
unable to commit after sync through account，no other popup or hits about what went wrong about the previous sync action.

### ISSUE THREAD

**Issue by ghx3** [microsoft/vscode-remote-repositories-github#390]
ADD ISSUE DESCRIPTION HERE

Version: 1.84.2
Commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 Edg/119.0.0.0
Embedder: github.dev

Extension version: 0.40.0

**Comment by zhraa1992** [comment]
[``](url)

**Comment by joyceerhl** [comment]
Sorry for the delayed response here, can you share a repo where this repros for you or any error logs from the output channel?

**Comment by joyceerhl** [comment]
Please reopen if this repros still for you, thanks!
