### ISSUE TITLE
Can't open vscode-python

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-remote-repositories-github#40]
- Run "Open Repository"
- Type `microsoft/vscode-python`
- I get other repos but not the vscode-python repo

is this because it's a fork?
![image](https://user-images.githubusercontent.com/323878/126011147-35bebf14-d124-4e9a-8b7b-b5ff9d98464f.png)

**Comment by joyceerhl** [comment]
This is because GitHub search doesn't include forks by default. We have to specify `fork:true` in the query https://docs.github.com/en/github/searching-for-information-on-github/searching-on-github/searching-in-forks
