### ISSUE TITLE
Extension seeming not showing up, once installed. 

### ISSUE THREAD

**Issue by DanGoldwater1** [microsoft/vscode-remote-repositories-github#406]
With the extension installed, I can't find any commands which relate to it. It also doesn't show up in the sidebar. 
![image](https://github.com/microsoft/vscode-remote-repositories-github/assets/100152081/7b19863e-1e98-4bf3-bfe0-d26feb8d4016)

![image](https://github.com/microsoft/vscode-remote-repositories-github/assets/100152081/d17b0f21-5726-464a-9969-bc2a90cc5de3)
These are my settings:
![image](https://github.com/microsoft/vscode-remote-repositories-github/assets/100152081/bce83e6a-8827-48a6-a925-7de1aa5f8a52)

**Comment by joyceerhl** [comment]
Are the Remote Repositories commands like `Open Remote Repository` available?
