### ISSUE TITLE
وكيل المستخدم: Mozilla/5.0 (Linux؛ Android 10؛ K) 

### ISSUE THREAD

**Issue by ibbrahiim** [microsoft/vscode-remote-repositories-github#408]
ADD ISSUE DESCRIPTION HERE

Version: 1.85.1
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
User Agent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Mobile Safari/537.36
Embedder: vscode.dev

Extension version: 0.40.0

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode-remote-repositories-github/issues/407
```

**Comment by ibbrahiim** [comment]
> ADD ISSUE DESCRIPTION HERE
> 
> Version: 1.85.1
> Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
> User Agent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Mobile Safari/537.36
> Embedder: vscode.dev
> 
> Extension version: 0.40.0
> 
> ```[tasklist]
> ### Tasks
> ```

**Comment by joyceerhl** [comment]
Please provide more details if you're experiencing an issue using vscode.dev, thanks!
