### ISSUE TITLE
My.website

### ISSUE THREAD

**Issue by rathanagithu** [microsoft/vscode-remote-repositories-github#411]
ADD ISSUE DESCRIPTION HERE

Version: 1.85.1
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
User Agent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
Embedder: vscode.dev

Extension version: 0.40.0

**Comment by joyceerhl** [comment]
Please provide more details if you're experiencing an issue using vscode.dev, thanks!
