### ISSUE TITLE
CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by batman038** [microsoft/vscode-remote-repositories-github#413]
ADD ISSUE DESCRIPTION HERE

Version: 1.85.1
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
User Agent: Mozilla/5.0 (Android 12; Mobile; rv:121.0) Gecko/121.0 Firefox/121.0
Embedder: vscode.dev

Extension version: 0.40.0

**Comment by batman038** [comment]
CODE_OF_CONDUCT.md

**Comment by Katrawud** [comment]
> ADD ISSUE DESCRIPTION HERE
> 
> Version: 1.85.1
> Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
> User Agent: Mozilla/5.0 (Android 12; Mobile; rv:121.0) Gecko/121.0 Firefox/121.0
> Embedder: vscode.dev
> 
> Extension version: 0.40.0
>
