### ISSUE TITLE
Functionality of Pull Request review for Azure DevOps

### ISSUE THREAD

**Issue by TestingD-BALTA** [microsoft/vscode-remote-repositories-github#415]
Please add functionality of performing Pull Requests (review, comment, create) from VSCode. This is very important and largest drawback Azure DevOps comparing to other competitors like GitHub, BitBucket, GitLab - which have very good integration with VSCode.

**Comment by joyceerhl** [comment]
Duplicate of https://github.com/microsoft/vscode-remote-repositories-github/issues/282
