### ISSUE TITLE
Bicep extension stops working when this is installed.

### ISSUE THREAD

**Issue by kpirkoBLM** [microsoft/vscode-remote-repositories-github#425]
I lose all telesense on a bicep file and when I go to the start a new file. Select a language bicep is not an option anymore. seems like these two extensions wont work together. https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-bicep

**Comment by joyceerhl** [comment]
Please consider filing an issue for the Bicep extension to support virtual workspaces. https://code.visualstudio.com/api/extension-guides/virtual-workspaces
