### ISSUE TITLE
Extension activation failed

### ISSUE THREAD

**Issue by celialovesdata** [microsoft/vscode-remote-repositories-github#426]
Type: <b>Bug</b>

TypeError: Cannot read properties of undefined (reading 'enabled')

Extension version: 0.62.0
VS Code version: Code 1.86.0 (Universal) (05047486b6df5eb8d44b2ecd70ea3bdf775fd937, 2024-01-31T10:29:15.765Z)
OS version: Darwin arm64 23.3.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|5, 4, 3|
|Memory (System)|16.00GB (0.16GB free)|
|Process Argv|--crash-reporter-id 2797ddda-9f39-4318-ba2a-89913148a9a5|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30951796
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementsc:30887149
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
dsvsc019b:30953937
7j2b6412:30949929
bg6jg535:30956215

```

</details>

**Comment by joyceerhl** [comment]
Can you please share the extensions you have installed and their versions? I cannot reproduce this error. Thanks!

**Comment by chris1640** [comment]
> Type: Bug
> 
> TypeError: Cannot read properties of undefined (reading 'enabled')
> 
> Extension version: 0.62.0 VS Code version: Code 1.86.0 (Universal) (05047486b6df5eb8d44b2ecd70ea3bdf775fd937, 2024-01-31T10:29:15.765Z) OS version: Darwin arm64 23.3.0 Modes:
> 
> System Info
> A/B Experiments

g i

**Comment by joyceerhl** [comment]
Please reopen when you can share additional info. Thanks!
