### ISSUE TITLE
Flag "D" (deleted) when i am doing a commit is not appearing on web vscode

### ISSUE THREAD

**Issue by yurivenancio30** [microsoft/vscode-remote-repositories-github#429]
The flag "D", that shows what was deleted, is not appearing in web vscode when i am using source control to manage commits. Why it is happenning? 
![image](https://github.com/microsoft/vscode/assets/105806503/4e25193b-5537-4fec-96d4-088b2fd8a268)

**Comment by lszomoru** [comment]
@joyceerhl, do you mind taking a look? Thank you!

**Comment by meganrogge** [comment]
@joyceerhl not seeing this, must not be released

![Image](https://github.com/microsoft/vscode-remote-repositories-github/assets/29464607/4dddc870-ecc7-42e2-82f5-cf0266db1d8e)

**Comment by joyceerhl** [comment]
Fix needs tomorrow's pre-release to be verified

**Comment by lucasfcnunes** [comment]
> Fix needs tomorrow's pre-release to be verified

Why was it closed, @joyceerhl? It's happening to me too.
*I deleted `README.md` (D) and modified `LICENSE-CODE` (M).

![image](https://github.com/microsoft/vscode-remote-repositories-github/assets/29926675/4d68d9d4-4dd4-4a07-98b7-7d42b1ea0a7a)

### About

```
Version: 1.85.2
Commit: 8b3775030ed1a69b13e4f4c628c612102e30a681
Date: 2024-01-18T06:35:55.911Z
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 Edg/123.0.0.0
```

**Comment by lucasfcnunes** [comment]
> @joyceerhl not seeing this, must not be released
> 
> ![Image](https://private-user-images.githubusercontent.com/29464607/306798833-4dddc870-ecc7-42e2-82f5-cf0266db1d8e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1NTcyOTgsIm5iZiI6MTcwODU1Njk5OCwicGF0aCI6Ii8yOTQ2NDYwNy8zMDY3OTg4MzMtNGRkZGM4NzAtZWNjNy00MmUyLTgyZjUtY2YwMjY2ZGIxZDhlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIxVDIzMDk1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0MmVhYjhkMmQxMTc2OTBlYzlkMjM1MzE5MjUyNjVjZjgwMTZkMGI1YzNjZmI2MTVlZWVhOTFhN2MzMzFiNmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oGmv65LrT4n-1YCRiaPFSfFn57ckXG_5VrNSsxnwYzc)

@meganrogge

The missing [D in the git short status](https://git-scm.com/docs/git-status#_short_format:~:text=A%20%3D%20added-,D%20%3D%20deleted,-R%20%3D%20renamed) is the issue.

**Comment by andreamah** [comment]
<img  alt="image" src="https://github.com/microsoft/vscode-remote-repositories-github/assets/31675041/b8184d61-8adf-4b53-8e63-5c7ff9e6f54f">

Still not getting it today,

<img alt="image" src="https://github.com/microsoft/vscode-remote-repositories-github/assets/31675041/6b90f13d-e808-4eab-99b7-47edcaedc7ac">

**Comment by joyceerhl** [comment]
Autopublish last night failed due an ADO outage, just kicked off a new prerelease publishing run

**Comment by rzhao271** [comment]
Verified on insiders.vscode.dev.

**Comment by lucasfcnunes** [comment]
It's working! Thanks!

Q: Where was the fix committed? I don't see a reference here. Was it done in a private repo?

![image](https://github.com/microsoft/vscode-remote-repositories-github/assets/29926675/ef9551c3-fcfb-4f60-bf10-2f7bd6451d5b)

**Comment by rzhao271** [comment]
Yes
