### ISSUE TITLE
Shared vscode dev link is not opening the file in the shared link

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode-remote-repositories-github#446]
- Open insiders.vscode.dev with vscode-docs repo
- Open v1_89.md
- Share the file using vscode.dev link 
- Paste the link in another browser Eg: https://insiders.vscode.dev/github.com/microsoft/vscode-docs/blob/main/release-notes/v1_89.md#1

🐛 File is not opened

**Comment by joyceerhl** [comment]
This works for me, does it repro still @sandy081?

**Comment by sandy081** [comment]
Its working for me now.
