### ISSUE TITLE
Folders missing in File Explorer

### ISSUE THREAD

**Issue by burkeholland** [microsoft/vscode-remote-repositories-github#47]
VS Code: 1.59.0
GitHub Repositories: 0.13.0

Not all folders in the repo are shown in the file explorer. For instance, for the [MSFT Learn PR repo] (https://github.com/microsoftdocs/learn-pr) (fork), the Azure folder is present in GitHub, but not in the VS Code file explorer. It should be noted that this folder is quite large.

### GitHub
![image](https://user-images.githubusercontent.com/686963/128601268-e4ded3e6-9e26-45b5-8842-2ab2b5e553e3.png)

### File Explorer (Remote Repositories)
![image](https://user-images.githubusercontent.com/686963/128601319-91b3e51b-f4e9-4917-be9f-2690841699ac.png)

The files in that folder are still accessible via the Command Palette if referenced directly. 

The VS Code output window shows the following error for Remote Repositories....

````
[2021-08-07 13:02:56:608] Running on the desktop; workspaceId=bd97b5f317aabceb03c03c4e45c1d328; storageUri=file:///c:/Users/buhollan/AppData/Roaming/Code/User/globalStorage/github.remotehub
[2021-08-07 13:02:56:857] [Experimental] Prefetching tree for b3fb23390c5ec7fa7be2643d60eec1160d52a7cd...
[2021-08-07 13:03:00:516] Loading file tree for path=.vscode failed
HttpError: Not Found
````

**Comment by sukumo28** [comment]
same problem on https://github.com/microsoft/vscode-test  
`sample/test` dir is shown. (other files/dirs in `sample` dir are shown)  
`sample/test` is not so large.  

VS Code: 1.59.0
GitHub Repositories: 0.13.0

**Comment by alexweininger** [comment]
I'm experiencing a similar bug. The GitHub actions workflow files are missing in the explorer. Here is a link to the repo: https://github.com/alexweininger/vanilla-basic-04

![image](https://user-images.githubusercontent.com/12476526/129949396-2d7138b6-11cc-4d7c-9be2-728ad7626ec2.png)

![image](https://user-images.githubusercontent.com/12476526/129949431-161e72c8-3473-4edb-8f19-80c048f1ba6b.png)

<details>
<summary>System info</summary>

CPUs | Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)
-- | --
GPU Status | 2d_canvas: enabled gpu_compositing: enabled metal: disabled_off multiple_raster_threads: enabled_on oop_rasterization: enabled opengl: enabled_on rasterization: enabled skia_renderer: disabled_off_ok video_decode: enabled webgl: enabled webgl2: enabled
Load (avg) | 2, 2, 3
Memory (System) | 16.00GB (0.11GB free)
Process Argv | --crash-reporter-id eb6f422b-5935-4d6a-89db-b06c6aac18f0
Screen Reader | no
VM | 0%


</details>

<details>
<summary>A/B info</summary>

vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
vshan820:30294714
pythonvsuse255:30319630
3f5j7703:30294757
vscod805cf:30301675
vsccppwtct:30312693
bridge0708:30335490
pygetstartedt2:30353727
dockerwalkthru:30348713
bridge0723:30353136
javagetstartedt:30350119

</details>

**Comment by eamodio** [comment]
The original issue should be fixed in the latest release. While @alexweininger your issue is a workflow permissions issue which is fixed in the latest insiders version of the extension.

If you want to verify this fix, you can install the GitHub Repositories (Insiders) edition from [here](https://marketplace.visualstudio.com/items?itemName=GitHub.remotehub-insiders).

Please be sure to disable or uninstall the stable version of GitHub Repositories first. Also note, that no data is shared between the insiders and stable editions.
