### ISSUE TITLE
[Feature request] It would be helpful to allow users to create folders and categorize multiple opened remote repositories.

### ISSUE THREAD

**Issue by faithk7** [microsoft/vscode-remote-repositories-github#471]
Sometimes, I use remote repositories as a code reading tool and open multiple repos. It would be great if I could create folders to categorize different repos.

**Comment by Rock1raw** [comment]
- [x] [](url)

**Comment by joyceerhl** [comment]
On VS Code desktop, you can create workspaces from one or more remote repositories.
