### ISSUE TITLE
I can´t commit & push from a remote open in VSC

### ISSUE THREAD

**Issue by alfa7g7** [microsoft/vscode-remote-repositories-github#474]
Good morning i can´t commit & push from VSC after open my remote repo from github... and only get the message Unable to commit.
![image](https://github.com/user-attachments/assets/6e5fb5f6-3c0a-4139-9781-98a3af26d174)

**Comment by joyceerhl** [comment]
Are you trying to commit a particularly large file? Is there anything in the GitHub Repositories output channel?

**Comment by alfa7g7** [comment]
it has 200mb

**Comment by alfa7g7** [comment]
Was a problem with trash in memory but i reset all output then the size was reduced. Finally with the new size i could commited
