### ISSUE TITLE
Support for self-hosted Github Enterprise

### ISSUE THREAD

**Issue by maxwellainatchi** [microsoft/vscode-remote-repositories-github#476]
Currently, self-hosted Github Enterprise doesn't seem to be supported - rather surprising, as VSCode has native authentication support for self-hosted GHE, and the other first-party VSCode extensions that I've used all support self-hosted GHE. Is there a technical reason preventing support?

**Comment by joyceerhl** [comment]
Duplicate https://github.com/microsoft/vscode-remote-repositories-github/issues/4
