### ISSUE TITLE
Extension activation failed

### ISSUE THREAD

**Issue by MUNEEBAZAM96** [microsoft/vscode-remote-repositories-github#493]
Type: <b>Bug</b>

Error: a provider for the scheme 'github' is already registered

Extension version: 0.64.0
VS Code version: Cursor 0.42.5 (001668006cc714afd397f4ef0d52862f5a095530, 2024-11-14T00:33:36.512Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.74GB (0.82GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by joyceerhl** [comment]
Please file issues for Cursor on their issue tracker.
