### ISSUE TITLE
Github Web Editor: Download Full Content After Cancelling Initial Notification

### ISSUE THREAD

**Issue by sahin52** [microsoft/vscode-remote-repositories-github#496]
- Github Web Editor asks for downloading full content when you first use github.dev in a repo. For example: https://github.dev/OpenCPN/OpenCPN  
![Image](https://github.com/user-attachments/assets/784fca3f-5cc0-4a34-92f4-1d0165f8ca32)
- But when you cancel that notification, you can't download full content again. There isn't an option for it(or I couldn't find)  

### How to reproduce:
- Go to any github.dev page and go to settings -> githubRepositories.indexing.maxIndexSize
- Set it to a small number, for example 50.
- Go to https://github.dev/OpenCPN/OpenCPN
- This repository index is more than 50 mb and this notification will pop up, click on cancel. 
- When you search for a text, it doesn't search well, since the repo is not fully downloaded
- You can't find a button to fully download again.

Related issue: https://github.com/microsoft/vscode/issues/234206

**Comment by sahin52** [comment]
Also, clicking on Download Full Content, restarts the process. As a result it takes a lot of time

**Comment by joyceerhl** [comment]
You can reenable downloading repository indexes by choosing "Remote Repositories: Enable Repository Indexing" from the command palette (Ctrl+Shift+P). The next time you trigger a text search, we should attempt to download the repository index again.
