### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Thomastrainiac** [microsoft/vscode-remote-repositories-github#50]
- Issue Type: `Performance`
- Extension Name: `remotehub`
- Extension Version: `0.13.3`
- OS Version: `Windows_NT x64 10.0.22000`
- VS Code version: `1.60.0-insider`

[GitHub.remotehub-unresponsive.cpuprofile.txt](https://github.com/microsoft/vscode-remote-repositories-github/files/7016222/GitHub.remotehub-unresponsive.cpuprofile.txt)

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by joyceerhl** [comment]
The callstack here seems to point back into the loader taking a long time: 
<img width="1547" alt="image" src="https://user-images.githubusercontent.com/30305945/206028594-77636880-ab9b-486a-b728-da78c15c5065.png">

Does this reproduce if you use Extension Bisect or disable all other extensions besides GitHub.remotehub?
