### ISSUE TITLE
Cannot see Organizational Repositories

### ISSUE THREAD

**Issue by robinhalabicki** [microsoft/vscode-remote-repositories-github#52]
I am logged into github in VS Code, and Authorized the app when I logged in.   I can only see my person repo's and not the private organizational ones.

I am the Org Owner.   Did I miss something?  I am able to clone the repo using "Clone Repository" button and the URL.  

I cannot via "Open Github Repository" button.

**Comment by eamodio** [comment]
Are you not seeing the repositories in the picker? Or are you unable to even paste in a repository url? If the former, please try typing the organization name in the picker -- so like `microsoft/` that should filter the shown repositories to that org/user.

**Comment by robinhalabicki** [comment]
I cannot see any Organization Repositories in the picker, I can enter the URL

**Comment by joyceerhl** [comment]
This should have been fixed in the February 2022 release. Please file a new issue if this persists.
