### ISSUE TITLE
Can't see folders with special characters

### ISSUE THREAD

**Issue by amuck-gorilla** [microsoft/vscode-remote-repositories-github#55]
When the Github Repositories extension attempts to clone or create a folder locally that has certain characters in its name, (I've only tested "`:`" and "`"`"), the folder is not created in the filesystem, which can also set off a host of other errors.

**Comment by eamodio** [comment]
Do you have an example of a repository with such characters? I thought `:` wasn't allow on any file system.

**Comment by joyceerhl** [comment]
Please provide an example of a repository with such characters for us to investigate.
