### ISSUE TITLE
Should work with other hosted Git services

### ISSUE THREAD

**Issue by thany** [microsoft/vscode-remote-repositories-github#56]
Like Gitlab, Codeberg, Bitbucket, SourceForge, Azure Repos, etc.

Or literally any privately-hosted Git repo, since in the background it's most likely checking out the repo, and comitting to it. If so, it should work with any random Git repo.

**Comment by eamodio** [comment]
Azure Repos support is coming, but we don't currently have any plans for other services.

**Comment by thany** [comment]
Can you *make* plans for them? 😉

Please don't only support Microsoft stuff. There's *so* much more in the world.
