### ISSUE TITLE
Error opening PRs in Github web editor

### ISSUE THREAD

**Issue by cdce8p** [microsoft/vscode-remote-repositories-github#57]
When I try to open a PR in the Github web editor (by pressing `.`), I get an error message:
```
Unable to open '....'
```

Further investigation leads me to believe that the issue might be caused by the `Github Repositories` extension. Opening the output panel for it, I see this message:
```
[2021-09-08 21:11:25:777] Failed to get repository info for 'Un-index/vscode'
GraphqlResponseError: Request failed due to following response errors:
 - Could not resolve to a PullRequest with the number of 132524.
```

The error is for a PR I randomly picked from the `vscode` repo: https://github.com/microsoft/vscode/pull/132524
The issue is reproducible for different PRs from different repos. The only requirement seems to be that the PR is coming from a different fork, quite common when working on open source projects.

Although I'm not completely certain, I believe the issue was introduced with the last update this month. It worked last month.

**Comment by eamodio** [comment]
This should now be resolved -- please let me know if you are still seeing issues.
