### ISSUE TITLE
Source?

### ISSUE THREAD

**Issue by GitMensch** [microsoft/vscode-remote-repositories-github#6]
The README states that this repo is for additional docs and providing feedback; this repo is under [CC BY 4.0](https://github.com/microsoft/vscode-remote-repositories-github/blob/main/LICENSE); "the code" is under [MIT](https://github.com/microsoft/vscode-remote-repositories-github/blob/main/LICENSE-CODE). The "binary" extension vsix, is - as other extensions from Microsoft - distributed under "use for whatever you like but only with Microsoft VS code binaries" https://marketplace.visualstudio.com/items/GitHub.remotehub/license

So... where is the actual code of the extension for review? Is the code under MIT (so also could be used to self-build for a self-build version of vscode or for use with Theia; possibly be extended/modified to be usable with other git hosting sites than Github)? If not: what does LICENSE-CODE applies to?

Please answer and be specific in the README, preventing these questions in the future.
Thanks!

**Comment by bamurtaugh** [comment]
Hi, thank you for your feedback!

Yes, this repo is under CC by 4.0 (the [LICENSE](https://github.com/microsoft/vscode-remote-repositories-github/blob/main/LICENSE) file in this repo). 

The [LICENSE-CODE](https://github.com/microsoft/vscode-remote-repositories-github/blob/main/LICENSE-CODE) in this repo covers any code or snippets included in this repository itself. I have updated the README to help clarify this.

The code for the Remote Repositories extension is under the final license you link: https://marketplace.visualstudio.com/items/GitHub.remotehub/license. The repository is open source, but the code for the extension itself is not available.

**Comment by GitMensch** [comment]
Thank you for making the current state clear.
... next question - actually a feature request: Can Microsoft please "open source" the code for the extension itself?

**Comment by bamurtaugh** [comment]
Thank you for the interest! As a GitHub published extension tied to the GitHub service, open sourcing is not currently on the extension roadmap.
