### ISSUE TITLE
Commands are still mention "Remote Repositories"

### ISSUE THREAD

**Issue by sana-ajani** [microsoft/vscode-remote-repositories-github#60]
I think some of the language in the notifications and commands for GitHub Repositories still reference "Remote Repositories" or "RemoteHub" which can be confusing for users. 

- [ ] When you have GitHub Repositories Insiders installed, the commands to open a repo are still prepended with "Remote Repositories" instead of "GitHub Repositories" (none of the commands show up when you type in "GitHub Repository:" like the extension readme mentions)
![image](https://user-images.githubusercontent.com/9721254/135144012-dc4d7a85-77a3-491d-bbdd-3d78cad6c0f8.png)

- [ ] Install both the GitHub Repositories and the GitHub Repositories Insiders extensions and try to open up a repo. In the notification that pops up, the GitHub Repositories Insiders is referred to as RemoteHub insiders
![image](https://user-images.githubusercontent.com/9721254/135143783-5ede5096-020e-4497-b63e-58139d08b66d.png)

**Comment by joyceerhl** [comment]
This was fixed 2 months ago. I can't reproduce this behavior:
![image](https://user-images.githubusercontent.com/30305945/135166781-b9c34e8d-ea61-443d-8ee4-0501bcec915b.png)

 Do you happen to have pending updates for VS Code or GitHub repositories?

**Comment by sana-ajani** [comment]
Ah! Thanks, I had both RemoteHub insiders and Github repositories insiders installed! Thanks Joyce
