### ISSUE TITLE
Can not commit from github.dev

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode-remote-repositories-github#61]
https://github.dev/microsoft/vscode-docs/tree/vnext
Make a change to our release notes, try to commit -> error

Here's the output from the GitHub repositories output.
If I reload I still get the same problem.

```
[2021-10-01 12:36:25:198] eval
HttpError: Unexpected end of JSON input
```

**Comment by joyceerhl** [comment]
@isidorn Did you have the Insiders or Stable version of RemoteHub installed and does this repro with the Insiders version of RemoteHub? Would you mind setting `"remoteHub.logLevel": "info"`, then reloading and providing the logs from that?

**Comment by isidorn** [comment]
I had the stable version of RemoteHub.
I can not reproduce with the Insiders version of RemoteHub.

**Comment by joyceerhl** [comment]
Closing as I'm assuming this was fixed in an update based on https://github.com/microsoft/vscode-remote-repositories-github/issues/61#issuecomment-932345745
