### ISSUE TITLE
When typing anything in the branch name, there should be a button for it

### ISSUE THREAD

**Issue by Milo123459** [microsoft/vscode-remote-repositories-github#63]
In VSCode desktop:
![image](https://user-images.githubusercontent.com/50248166/133136221-b91f5f0c-5a47-446c-94c7-6d5eb5683998.png)
In Codespaces:
![image](https://user-images.githubusercontent.com/50248166/133136244-92c9405b-d8a8-479c-a687-6f9fc7a7602d.png)

I am suggesting that in Codespaces the behaviour is like it is in vscode desktop.

**Comment by joyceerhl** [comment]
Veriification steps:
1. Open a remote repositories repo (either in insiders.vscode.dev or in desktop VS Code)
2. Click on the SCM status bar item reflecting the current branch name to open the branch picker 
3. Type something into the input
4. Verify that the `Create new branch` and `Create new branch from...` entries still show up with text in the input
5. Verify that clicking on those entries behaves as expected (honors the existing input)
