### ISSUE TITLE
Searching in a PR finds results in deleted files

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-remote-repositories-github#65]
- Open https://github.dev/roblourens/testrepo/pull/3
- Search "hello"
- I get results in readme.md, which is deleted in that PR

![image](https://user-images.githubusercontent.com/323878/138195246-da0f7ea9-03b3-4b3f-a967-ccf344e4f640.png)

**Comment by JacksonKearl** [comment]
Tested with https://github.dev/JacksonKearl/RollDice-Discord/pull/15, can no longer reproduce.
