### ISSUE TITLE
Cannot open a remote repository.

### ISSUE THREAD

**Issue by Krebrov001** [microsoft/vscode-remote-repositories-github#66]
I cannot open a remote repository any way:
  - In the command pallet `GitHub Repositories: Open Repository...` gives the error message
    - `Command 'GitHub Repositories: Open Remote Repository...' resulted in an error (Running the contributed command: 'remoteHub.openRepository' failed.)`
  - `Open GitHub Repository...` from the remote indicator (the green button in the lower left corner of the status bar) does nothing, no error messages displayed.

I have tried with both **GitHub Repositories** and **GitHub Repositories (Insiders)**, and I still have the same problem.

I am using `Visual Studio Code - Insiders [Unsupported]` because I am using the **Custom CSS and JS Loader** extension.

**Comment by joyceerhl** [comment]
Closing as I haven't heard back--please let me know if the issue persists for you!
