### ISSUE TITLE
GitHub.dev cs files crashing website on safari

### ISSUE THREAD

**Issue by Jitoku** [microsoft/vscode-remote-repositories-github#73]
GitHub.dev crashes when opening c# files on safari (macOS Big Sur). This does not occur on Chrome.

**Comment by DragRedSim** [comment]
Also occurs on vscode.dev and insiders.vscode.dev, and occurs on Safari on iPad with C++ files (attempting to browse/edit the Marlin 3D printer firmware project).

**Comment by joyceerhl** [comment]
Sorry for the delayed response--are you able to reproduce this issue still and if so, can you please provide repro steps or a test repo that reliably induces this behavior?

**Comment by DragRedSim** [comment]
Still occurring for me. iPad Air 3, iOS 14.5.1.

Example file: http://vscode.dev/github/dragredsim/ArduinoTaikoController/taiko_controller/taiko_controller.ino - Arduino sketch, interpreted automatically by VSCode as C++. (Not designed to induce this crashing behaviour, but does so anyway.)
Second example: https://github.dev/MarlinFirmware/Marlin/blob/bugfix-2.1.x/Marlin/Version.h - this time, on a repo I don't have write access to; the browser still crashes.

Notably, I was able to browse/edit the same Arduino file using a GitPod instance, which also provides VSCode in the web browser, though in a different manner, without the browser crashing.

**Comment by joyceerhl** [comment]
Both those files load successfully for me on Safari (on desktop as well as mobile).

Which extensions do you have installed in vscode.dev and github.dev--if you have any installed, does the crashing persist after disabling all installed extensions?

**Comment by joyceerhl** [comment]
Closing this out as I haven't gotten a response on steps to repro. Please reopen if you can provide details--thanks!
