### ISSUE TITLE
Double "Go to repository" buttons in github.dev

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode-remote-repositories-github#75]
- Go to github.dev, i.e. https://github.dev/ataridotcom/gh-static-e2e
- Open hamburger menu
- :bug: Double "Go to repository" buttons, both work

![image](https://user-images.githubusercontent.com/25310137/138775549-7e092fbb-a234-4e71-97f1-d1eebfb35fdc.png)

I only have GitHub Repositories stable installed, and I'm using Stable version of VS Code

Don't see the same in VS Code for the Web at https://vscode.dev/github/ataridotcom/gh-static-e2e

**Comment by joyceerhl** [comment]
Fixed in the github.dev embedder.

**Comment by kimadeline** [comment]
verified:

![image](https://user-images.githubusercontent.com/51720070/144297914-dafe24c5-269d-486d-bf7c-cbde5fc13764.png)
