### ISSUE TITLE
DevOps could launch the new in-browser VS Code experience when clicking "Edit in Repos"

### ISSUE THREAD

**Issue by thomasp-ms** [microsoft/vscode-remote-repositories-github#76]
It would be very nice if the new in-browser VS Code was automatically launched when clicking "Edit in Repos" from DevOps (instead of the current DevOps editor.)

**Comment by joyceerhl** [comment]
@lszomoru is this feedback addressed by your work with Azure DevOps to add the '.' shortcut for Azure Repos?

**Comment by lszomoru** [comment]
@joyceerhl, I believe it does. Closing the issue for now.
