### ISSUE TITLE
Can't open branches with non-latin characters (github.dev)

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode-remote-repositories-github#78]
_Originally reported by @Katsute in https://github.com/github/feedback/discussions/5229_

Using the `.` command to open the online editor doesn't work if the branch contains encoded characters (ex: `@`)

If I go directly to a branch directly it works correctly
`https://github.dev/KatsuteDev/JCore/tree/enforce-timeouts@443b11e` (`enforce-timeouts@443b11e` is the branch)

the issue seems to be that when you go on GitHub the branch name is encoded (`@` → `%40`) which works properly on GitHub but the dev site seems to have issues resolving the branch
`https://github.dev/KatsuteDev/JCore/tree/enforce-timeouts%40443b11e` (there is no such branch `enforce-timeouts%40443b11e`)

**Comment by joyceerhl** [comment]
User confirmed that this has been fixed: https://github.com/github/feedback/discussions/5229#discussioncomment-1713447
