### ISSUE TITLE
Can't switch to latest code index commit, even if some are available

### ISSUE THREAD

**Issue by jepetty** [microsoft/vscode-remote-repositories-github#81]
I'm unable to enable the latest rich navigation commit on https://vscode.dev/azurerepos/devdiv/devdiv/vs-platform. When I look at network activity, I see there are responses for indexed commits for the branch that I'm on, but for some reason I can't select latest commit using the task bar.

I'm wondering if there's something wrong with the data we're sending that is causing none of the commits to be eligible for selection?

**Comment by jepetty** [comment]
@dbaeumer you might have some ideas :)

**Comment by jepetty** [comment]
It looks like we only set commits to browseable if the state is 5, when we should also be including 3

(for now - our team is changing our entire concept of "states" since right now it's... really bad 😄 )

**Comment by joyceerhl** [comment]
@jepetty does your PR fully resolve this issue, or should we leave it open to track the state refactor that @maridematte is driving?

**Comment by dbaeumer** [comment]
@jepetty can you comment on why Partial should be included. Partial doesn't sound like something complete :-)

**Comment by jepetty** [comment]
This resolves the issue in its current state! I'll describe our plans going forward below. Closing as there's no work to track on the VS Code Remote Repos side.

Dirk, you're right, Partial doesn't mean Complete, but currently Complete doesn't really mean Complete :) C# is a good example because we have repos with thousands of projects. If I try to index all projects, and one has an error (could be a single file is incorrectly processed), this commit will be marked as "Partial", though realistically the index is very usable (we have some repos that rarely get marked Complete because of their size/complexity - a separate issue that should be resolved ;) ). At the same time, if I try to index only 5 projects from that repo and all succeed with no errors, we would mark that index as Complete. Obviously, as a user I would way rather use the index with thousands of projects indexed rather than the one with 5, but today we don't represent that well (there's no granularity of quality between "Perfect" (as far as we know) and "Not Perfect")

The work Mari is doing is to start evaluating by overall completeness rather than us trying to decide how well we did while indexing (because we just can't). We'll start examining some heuristic about an index relative to that repository (project count, file count, total size of index) and use that to gauge completeness.

**Comment by rchiodo** [comment]
@jepetty do you have any steps we can take to verify?

**Comment by jepetty** [comment]
Yes! I'll write them out, but have also performed. This appears fixed in insiders.vscode.dev but not yet deployed to stable vscode.dev

1. Load msazure/One/Azure-Compute-Move with the Code Index browsing mode enabled (may need to try multiple repos to find a "Partial" state in step 3)
2. View network traffic to see the commits available by Code Index service for browsing -> https://prod.richnav.vsengsaas.visualstudio.com/api/v0.1/workspacesnapshot/all (I filter by just prod)
3. View the last commit in the list - this is the most recent commit we've indexed and ideally the one we'll show. If the state is 3, it should be affected by this change (see red highlight)
4. Assert that the commitId associated with the "Partial" snapshot is in fact the commit Id that's loaded (see green highlight)

**Comment by rchiodo** [comment]
Thanks. Sounds like you just verified it on insiders.

**Comment by jepetty** [comment]
Yup, that's right! In the future I'll put verification steps in the bug. Thanks for the help!
