### ISSUE TITLE
Allow entering shorthand repository url

### ISSUE THREAD

**Issue by d0ruk** [microsoft/vscode-remote-repositories-github#82]
Hello,

As well as inputting `https://github.com/microsoft/vscode-remote-repositories-github` to **Open remote repository**, allow writing `microsoft/vscode-remote-repositories-github`.

![image](https://user-images.githubusercontent.com/4752656/140456167-6506b3d1-dbf1-48f2-87a5-9840877fdc01.png)

**Comment by joyceerhl** [comment]
If you select the 'Open Repository from GitHub' option,

![image](https://user-images.githubusercontent.com/30305945/140539635-d356f18a-5614-4109-a0c7-9e9d1ac42045.png)

the next step is a search picker where you can enter a repo name, optionally prefixed with the repo owner:

![image](https://user-images.githubusercontent.com/30305945/140539684-53f88d68-f61a-410d-b112-c83060b6693c.png)

**Comment by d0ruk** [comment]
@joyceerhl 

You are right. I had to wait a bit for the search feature to boot up.

**Comment by joyceerhl** [comment]
We have had many similar issues where people want to put in a repo URL in the search picker, or enter a search in the repo URL. Wondering if we should reconsider the picker UX here

Currently the first step in the remote repository picker displays 'Open Repository from GitHub', 'Open Pull Request from GitHub', and then a cached list of recently-opened workspaces (various repos and various PRs, etc). We could merge those two steps, though it might make the queries slower.

 /cc @lszomoru

**Comment by d0ruk** [comment]
@joyceerhl 

Another idea. I have a file with a bunch of repo names like;

```
react-workspaces/react-workspaces-playground
bahdcoder/testingreact.dev
bradtraversy/vanillawebprojects
```

Is there a way to have vscode read line in from that file? Another solution would be to copy/paste a multiline string and it'll parse each line.

I would use that.
