### ISSUE TITLE
Signed out because reading stored authentication information failed

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-remote-repositories-github#83]
I had a locally-cloned repo (not virtual repo) open on VS Code desktop, and after a few hours I saw this error message:
![image](https://user-images.githubusercontent.com/30305945/140574660-58a15bac-ad1e-43f0-9333-cdc379c1be0d.png)

As a user it's not clear what I'm supposed to do about this situation.

1) If this happens because the token has expired or the like, should we add a 'Reauthenticate' button to this popup so the user can sign back in
2) I was under the impression that we automatically refresh tokens, so not sure why this scenario happens in the first place? /cc @TylerLeonhardt 

Logs from GitHub authentication extension output channel:

```
[Info  - 15:36:11.506] Reading sessions from keychain...
[Info  - 15:36:11.547] Getting sessions for user:email...
[Info  - 15:36:11.547] Getting sessions for all scopes...
[Trace  - 15:36:11.548] Token acquired from secret storage.
[Info  - 15:36:11.548] Got stored sessions!
[Trace  - 15:36:11.548] Read the following session from the keychain with the following scopes: repo,workflow
[Info  - 15:36:11.548] Got 1 verified sessions.
[Info  - 15:36:11.548] Got 0 sessions for user:email...
[Info  - 15:36:11.548] Got 1 sessions for all scopes...
[Info  - 15:36:11.562] Getting sessions for read:user,repo,user:email...
[Info  - 15:36:11.562] Got 0 sessions for read:user,repo,user:email...
[Info  - 15:36:21.283] Getting sessions for repo...
[Info  - 15:36:21.284] Got 0 sessions for repo...
[Info  - 15:51:27.166] Getting sessions for all scopes...
[Info  - 15:51:27.166] Got 1 sessions for all scopes...
[Info  - 15:51:35.819] Getting sessions for repo,workflow...
[Info  - 15:51:35.819] Got 1 sessions for repo,workflow...
[Info  - 16:02:26.397] Getting sessions for repo...
[Info  - 16:02:26.397] Got 0 sessions for repo...
[Info  - 16:50:58.103] Getting sessions for read:user,repo,user:email...
[Info  - 16:50:58.103] Got 0 sessions for read:user,repo,user:email...
[Info  - 17:50:28.461] Getting sessions for read:user,repo,user:email...
[Info  - 17:50:28.461] Got 0 sessions for read:user,repo,user:email...
[Info  - 18:07:50.644] Getting sessions for repo...
[Info  - 18:07:50.644] Got 0 sessions for repo...
```

**Comment by TylerLeonhardt** [comment]
GitHub tokens aren't refreshed because they don't need to be.

The logs don't say anything about a failure which is bizarre...

Anything interesting in dev tools/Remote Repositories Output channel?

**Comment by TylerLeonhardt** [comment]
Anything interesting in Dev Tools or GitHub Repositories Output channel?

**Comment by joyceerhl** [comment]
Briefly discussed this, it's likely to be the Azure DevOps side of the house

> we register azdo auth provider only when you use Azure DevOps
Which means that code that refreshes the token only runs if you use Azure DevOps
But that could mean the token expires if you haven't used Azure DevOps in ages

There's no indication which auth provider the user was signed out of. The fact that this message comes from 'GitHub Repositories' makes it even more confusing. cc @lszomoru as this relates to splitting Azure Repos support out into a separate extension

**Comment by TylerLeonhardt** [comment]
I was partially wrong. Apparently we activate the Azure DevOps auth provider if the setting `azureRepos.enabled` is true:

https://github.com/microsoft/vscode-remotehub/blob/252976119b8da952542c62b6ed486bc3894632ae/src/extension.ts#L245

but if you haven't explicitly set this, then I think what I said above is "functionally true".

**Comment by TylerLeonhardt** [comment]
@joyceerhl next time this happens, can you share what's in Dev Tools?

**Comment by joyceerhl** [comment]
Will do :)

**Comment by OranguTech** [comment]
I know this is a bit old, but possibly related to [#145189](https://github.com/microsoft/vscode/issues/145189)?

**Comment by joyceerhl** [comment]
I haven't seen this lately, thus closing as likely stale
