### ISSUE TITLE
Login to Azure Repos

### ISSUE THREAD

**Issue by nurul-hudachair** [microsoft/vscode-remote-repositories-github#85]
How to get access to azure repos?
When accessing open remote repository in vs code, there are only options "Open Repository from GitHub" and "Open Pull Request from GitHub". 
If there is the documentation, where can I get it?
Thank you.

**Comment by joyceerhl** [comment]
From https://code.visualstudio.com/blogs/2021/10/20/vscode-dev#_github:
![image](https://user-images.githubusercontent.com/30305945/141261173-f4468c30-b3c6-42e6-bb21-39224353bff3.png)

We're adding support for Open Repository from Azure Repos in this milestone. cc @lszomoru

**Comment by joyceerhl** [comment]
If you are running RemoteHub on desktop, you can enter a URL into the Open Remote Repository picker:

![image](https://user-images.githubusercontent.com/30305945/141261528-85787eb9-c747-47a9-8e20-1f6ac514e64d.png)

**Comment by nurul-hudachair** [comment]
I got it. 
Thanks a lot @joyceerhl
