### ISSUE TITLE
No option to choose ssh clone for private repository

### ISSUE THREAD

**Issue by sealbro** [microsoft/vscode-remote-repositories-github#87]
At the moment, if you open private repository remotely and want to clone locally , then you need to login and there is no way to use an ssh key

For example, cloning takes place over `https` 
`https://github.com/microsoft/vscode-remote-repositories-github.git`
and there is no way to choose `ssh`
`git@github.com:microsoft/vscode-remote-repositories-github.git`
there is no possibility to clone and use ssh only

![image](https://user-images.githubusercontent.com/8067559/142039330-2a78db87-fa8e-4ab4-8625-cc3a8248479c.png)

**Comment by joyceerhl** [comment]
@lszomoru RemoteHub's 'Clone Repository Locally' command simply delegates to the builtin git extension's clone method. Does that extension support cloning via SSH? If not, this would be a feature request for vscode.git--I imagine something like a quickpick for choosing to clone via SSH or HTTPS, plus a setting to configure the default method.

**Comment by sealbro** [comment]
No, I can't find this setting in git extension 😢

**Comment by joyceerhl** [comment]
It looks like the builtin GitHub extension now has a setting to configure cloning via ssh: `"github.gitProtocol": "ssh"` https://github.com/microsoft/vscode/issues/145850 

GitHub Repositories can introduce a similar setting, what do you think @joaomoreno?

**Comment by joaomoreno** [comment]
Keen eye @joyceerhl!

Yeah I think that makes sense. Or provide a second level quick pick to select which protocol. I'm guessing you get the Octokit Repository, which knows both URLs? And I'm guessing you just pass the repo url as a string to `git.clone`?
