### ISSUE TITLE
Committing More Files Causes Authentication Error, Unable To Preview HTML Or Compile Java Files on GitHub Remote Workspace

### ISSUE THREAD

**Issue by ENTPRESTIGIOUS** [microsoft/vscode-remote-repositories-github#89]
I don't know if it's the fact that i've committed too many files at once but whenever I do, it popups an error saying that my authentication failed and that there's a button that says re-authenticate. However, the button doesn't do anything. 

Also, I've realized that whenever I put my file into the GitHub remote workspace, I am not allowed to compile or preview my html files using a VSCode extension. I've even made it a trusted workspace. What seems to be the problem?

**Comment by joyceerhl** [comment]
> authentication failed and that there's a button that says re-authenticate

Are you looking at a repository in an organization that enforces SAML for authentication? 

> I am not allowed to compile or preview my html files

GitHub Repositories workspaces are virtual workspaces. To compile and run files you will need to clone the repository locally or open it in a GitHub Codespace.

**Comment by ENTPRESTIGIOUS** [comment]
> Are you looking at a repository in an organization that enforces SAML for authentication?
Umm no because I'm using a GitHub Repository workspace.

> GitHub Repositories workspaces are virtual workspaces. To compile and run files you will need to clone the repository locally or open it in a GitHub Codespace.

Right but I guess having this extension to making the repository workspace into a temporary local workspace doesn't work then.

**Comment by joyceerhl** [comment]
Are you looking at a private repository or a publicly accessible one? Do you only have trouble committing changes, i.e. you can browse the repository contents without issues?

Could you enable debug logging in your settings, reload, then provide the contents of the GitHub Repositories output channel when you see the error message about committing?

![image](https://user-images.githubusercontent.com/30305945/142710554-f1247868-1341-48fc-aba7-4ce743580edb.png)

**Comment by joyceerhl** [comment]
Closing as I haven't heard back for some time. Please reopen if you have additional information to share on this issue.
