### ISSUE TITLE
'Reauthenticate' button does nothing on HttpError: Bad credentials

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-remote-repositories-github#90]
https://user-images.githubusercontent.com/30305945/143907071-f144c4e4-8804-4d80-b35b-cd0e0ac2fa20.mp4

**Comment by joyceerhl** [comment]
This code is the culprit

```ts
return await authentication.getSession('github', authorizationScopes, {
    createIfNone: true,
    forceNewSession: force,
});
```

which causes the getSession API to throw
```
Error: Invalid combination of options. Please remove one of the following: forceNewSession, createIfNone\n    at s.doGetSession (vscode-file://vscode-app/c:/Users/huer/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1696:2415)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async s.$getSession (vscode-file://vscode-app/c:/Users/huer/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1696:3868) {name: 'Error', message: 'Invalid combination of options. Please remov…the following: forceNewSession, createIfNone', stack: 'Error: Invalid combination of options. Please…orkbench/workbench.desktop.main.js:1696:3868)'}
```

and corresponds to this case in the GitHub authentication extension https://github.com/microsoft/vscode/blob/c71e201bed8ac00f7e653df8d110f1ee50ef8b5c/src/vs/workbench/api/browser/mainThreadAuthentication.ts#L215-L217 Has this combination of options always been invalid @TylerLeonhardt?

(As an aside, there's a lot of complexity that I don't fully understand the need for in RemoteHub's consumption of the `authentication.getSession` API. I don't have full context on this, but would love to trim some of these codepaths when we get a chance to sync.)

**Comment by TylerLeonhardt** [comment]
> Has this combination of options always been invalid @TylerLeonhardt?

I'm fairly certain it has... But I may have added it after a larger refactoring I did in October.

**Comment by SettingDust** [comment]
Still facing it in https://github.dev
